### ISSUE TITLE
LLPC fails with LLVM fatal error: "Instruction operands must be first-class values!"

### ISSUE THREAD

**Issue by afd** [GPUOpen-Drivers/llpc#1035]
Running LLPC with IR verification on one of the attached shaders leads to a fatal error.

llpc revision: c877ce1
llvm-project revision: 88613f67ca2e3e64cc1c7c4ccd47e126495e6e23

[tofile.zip](https://github.com/GPUOpen-Drivers/llpc/files/5531886/tofile.zip)

It looks like a problem to do with OpTypeVoid being the type of an OpPhi instruction.  Though unusual, this is allowed according to the SPIR-V specification.

```
amdllpc small.spv -val=false -verify-ir -o temp.out
Instruction operands must be first-class values!
  phi void [ undef, %.entry ], [ undef, %2 ]
in function 
ERROR: LLVM FATAL ERROR: Broken function found, compilation aborted!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
```

**Comment by afd** [comment]
I will add a shader-db test in due course.

**Comment by ruiling** [comment]
yes the spec does not has specific type requirement on OpPhi, But I really do not see any practical value of supporting such kind of usage. I guess the correct way to fix is disallowing such case.

**Comment by piotrAMD** [comment]
FWIW, this also came up recently in Khronos: https://gitlab.khronos.org/spirv/SPIR-V/-/issues/614.

**Comment by afd** [comment]
The only use case I see is the following:

- a SPIR-V to SPIR-V optimization tool may well have a transformation that moves OpFunctionCall instructions around, for example propagating such an instruction into the predecessors of a basic block and resolving their results with OpPhi.  This could enable partial specialization, for example.

- When a function returns void this would lead to void arguments to an OpPhi, *or* to the function movement optimization doing something special regarding the void case

...and this would only matter if the result of the original function call was actually used - it's hard to see reasons for using void results.

**Comment by ruiling** [comment]
I know the case sounds like a possible candidate use-case, but I think the question here is under what kind of case we care the void return value of a function. IMHO, we don't need to distinguish between two void values, so no need to merge them with a OpPhi. I still hope the spec be changed on this unless we really need phi with void type for any real-world usage.

**Comment by afd** [comment]
Yes, that sounds reasonable to me. Let’s await a decision on the spec I guess.

**Comment by ruiling** [comment]
Let's close this as spec has been update.
