### ISSUE TITLE
LLPC fails assertion in LLVM: "Initializer for struct element doesn't match!"

### ISSUE THREAD

**Issue by afd** [GPUOpen-Drivers/llpc#1036]
Running LLPC with IR verification on one of the attached shaders leads to an assertion failure.

llpc revision: c877ce1
llvm-project revision: 88613f67ca2e3e64cc1c7c4ccd47e126495e6e23

[tofile.zip](https://github.com/GPUOpen-Drivers/llpc/files/5531919/tofile.zip)

```
amdllpc small.spv -val=false -verify-ir -o temp.out
amdllpc: /vulkandriver/drivers/llvm-project/llvm/lib/IR/Constants.cpp:1155: llvm::ConstantAggregate::ConstantAggregate(llvm::Type *, llvm::Value::ValueTy, ArrayRef<llvm::Constant *>): Assertion `V[I]->getType() == ST->getTypeAtIndex(I) && "Initializer for struct element doesn't match!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /data2/gfautowork/llpc-from-docker/amdllpc small.spv -val=false -verify-ir -o temp.out 
1.	Running pass 'Function Pass Manager' on module 'llpcfragment5'.
2.	Running pass 'Combine redundant instructions' on function '@main'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it)
```

**Comment by afd** [comment]
I will add a shader-db test in due course.

**Comment by ruiling** [comment]
I tried latest dev branch, the issue disappear. should be fixed by somebody. @afd Could you help verify?

**Comment by afd** [comment]
Yes - I think we can close this as independently fixed.  If it turns out not to be fixed and triggerable by some other test case then the fuzzer will probably find it again and we can open another issue.
