### ISSUE TITLE
LLPC fails assertion in LLVM: "Invalid type for pointer element!"

### ISSUE THREAD

**Issue by afd** [GPUOpen-Drivers/llpc#1037]
Running LLPC with IR verification on one of the attached shaders leads to an assertion failure.

Like #1035, the SPIR-V involves OpPhi on OpTypeVoid, which (though unusual) is valid according to the spec.

llpc revision: c877ce1
llvm-project revision: 88613f67ca2e3e64cc1c7c4ccd47e126495e6e23

[tofile.zip](https://github.com/GPUOpen-Drivers/llpc/files/5531956/tofile.zip)

```
amdllpc small.spv -val=false -verify-ir -o temp.out
amdllpc: /vulkandriver/drivers/llvm-project/llvm/lib/IR/Type.cpp:661: static llvm::PointerType *llvm::PointerType::get(llvm::Type *, unsigned int): Assertion `isValidElementType(EltTy) && "Invalid type for pointer element!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /data2/gfautowork/llpc-from-docker/amdllpc small.spv -val=false -verify-ir -o temp.out 
1.	Running pass 'LLPC translate SPIR-V binary to LLVM IR' on module 'llpcfragment5'.
```

**Comment by ruiling** [comment]
Let's close this as spec has been updated to disallow this.
