### ISSUE TITLE
Regression in relocatable shaders caused by llvm-project change

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#1047]
Many of our internal tests are now failing when using relocatable shader because of https://github.com/llvm/llvm-project/commit/1124bf4ab7777448b994fa399022f1a8822c8295.

I'm guessing a bit is being set for a fetch shader or a color export shader, but it should not be set in general.  However, the merging of rsrc1 is simply a bitwise-or, which would not know this.

This error occurs in some of the (Sascha Willems Vulkan examples](https://github.com/SaschaWillems/Vulkan).  The [high dynamic range](https://github.com/SaschaWillems/Vulkan#02---high-dynamic-range) example is one where a difference can be observed.  I cannot see it with my untrained eye, but it is easily picked when comparing the images with an image comparison tool.

**Comment by Flakebi** [comment]
The flags are at different places for different shader types, so my first guess is that after or-ing the flags, some flag may be set that should not be enabled at all.
For reference, MEM_ORDERED and WGP_MODE are at different positions, depending on the shader type.
DEBUG_MODE, IEEE_MODE (always off for us), PRIV, DX10_CLAMP, FLOAT_MODE and PRIORITY are the flags that were not set for graphics shaders before.

It seems like DX10_CLAMP is enabled by default and FLOAT_MODE is set to 0xf0 (240).

How do I enable relocatable shaders to reproduce this?
I tried `LlpcOptions,-enable-relocatable-shader-elf`, which does not run (though I didn’t look into the reason) and `LlpcOptions,-use-relocatable-shader-elf`, which shows corruptions even with that patch reverted.

**Comment by s-perron** [comment]
> How do I enable relocatable shaders to reproduce this?

I add `EnableRelocatableShaders 1`.

The problem is the float mode.  I already have a fix in LGC for this.

**Comment by Flakebi** [comment]
Nice, thanks!

`EnableRelocatableShaders,1` seems to have the same effect as `-use-relocatable-shader-elf`.
The visual difference in the HDR example is the reflection inside the teapot btw, the corrupt version looks smeary and the houses are not looking great.
I can confirm that your patch fixes that.
