### ISSUE TITLE
LLPC compiles ambiguous code segment

### ISSUE THREAD

**Issue by tsymalla** [GPUOpen-Drivers/llpc#1053]
```
(LLVM (http://llvm.org/):
  LLVM version 12.0.0git
  DEBUG build with assertions.
  Default target: x86_64-unknown-linux-gnu)
```

Below is a GLSL fragment shader containing the following code:

```
#version 430

in vec4 inColor;
out vec4 outColor;

void main() {
    const int x = 10 *+ int(inColor.x);
    outColor = x * inColor;
}
```

The following command seems to work properly:

`amdllpc --emit-llvm test.frag`

The question is: what does `10 *+ int(inColor.x)` compile to? The IR looks something like this:

`%27 = fptosi float %20 to i32
  %28 = mul i32 %27, 10
  %29 = sitofp i32 %28 to float`

So it seems like just the multiplication gets evaluated, the add operation gets ignored. The problem is, reading this line could could also be understood as `(10 * 0) + int(inColor.x)` instead of `10 * int(inColor.x)`.

**Comment by Flakebi** [comment]
I think the + is just interpreted as a positive sign: `10 * (+int(inColor.x))`, similar to `10 * (-int(inColor.x))`.
A quick glimpse at the [glsl spec](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.40.pdf) says that unary operators (+, -, ~, !) have a higher precedence than multiplication and division.

**Comment by tsymalla** [comment]
Sounds reasonable. Thanks!
