### ISSUE TITLE
[CI] Rebuilding amdvlk fails during repo init

### ISSUE THREAD

**Issue by Flakebi** [GPUOpen-Drivers/llpc#1086]
The last few builds of the base image failed during the repo checkout: E.g. https://github.com/GPUOpen-Drivers/llpc/runs/1523871974?check_suite_focus=true
(Last succeeding build: https://github.com/GPUOpen-Drivers/llpc/runs/1508002982?check_suite_focus=true)

Looks like a problem with python 2/3 maybe?

cc @kuhar

**Comment by kuhar** [comment]
Thanks for reporting, @Flakebi. I submitted a PR with a fix. It was basically an issue with repo x ubuntu x python versioning.

**Comment by Flakebi** [comment]
Thanks for the quick fix!
