### ISSUE TITLE
Sanitizer CI builds fail on Ubuntu 20.04

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1092]
The error message is:
```
ERROR: ld.so: object '/usr/lib/llvm-9/lib/clang/9.0.0/lib/linux/libclang_rt.asan-x86_64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

A link to a failure: https://github.com/GPUOpen-Drivers/llpc/runs/1530537186?check_suite_focus=true.

**Comment by kuhar** [comment]
@Flakebi could you take a look?

**Comment by Flakebi** [comment]
@kuhar FYI, I’m currently looking at the failing tests with gcc. Part of it is caused by uninitialized variables but I still need to track down more bugs.
