### ISSUE TITLE
[CI] Sanitizer-enabled builds are out of disk again

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1179]
These builds have been failing since Feb 26, e.g., https://github.com/GPUOpen-Drivers/llpc/actions/runs/602716819

**Comment by Flakebi** [comment]
If there are no obvious things to make the build smaller, we can build only the compiler with sanitizers and exclude xgl and pal from this build.
The important part is to run unittests with sanitizers, which does not need xgl or pal.
