### ISSUE TITLE
New CI build failures after the latest LLPC and XGL merges

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1203]
Seems like the latest imports broke LLPC and XGL CI:
- https://github.com/GPUOpen-Drivers/llpc/actions/runs/725183732
- https://github.com/GPUOpen-Drivers/llpc/actions/runs/725930478

I opened a PR for the XGL cache-info warning: https://github.com/GPUOpen-Drivers/xgl/pull/109 and a PAL issue for unrecognized compiler flags: https://github.com/GPUOpen-Drivers/pal/issues/62

**Comment by kuhar** [comment]
cc @JaxLinAMD @Flakebi @amdrexu

**Comment by amdrexu** [comment]
Thank you. Jax will take a look and resolve it.

**Comment by JaxLinAMD** [comment]
@kuhar  what version of gcc is used? I didn't observe compile failure on ubuntu 18.04

**Comment by Flakebi** [comment]
The GitHub runners use Ubuntu 20.04 and gcc 9.3.0.
