### ISSUE TITLE
Investigate and re-enable phi-of-ops optimization in NewGVN

### ISSUE THREAD

**Issue by ruiling** [GPUOpen-Drivers/llpc#1206]
The existing phi-of-op optimization is buggy in NewGVN. Although there are recently some
patches by Florian to fix outstanding issues (https://reviews.llvm.org/D66924, https://reviews.llvm.org/D99987), the issue
that block us is still not fixed (https://bugs.llvm.org/show_bug.cgi?id=49873),
I haven't come up with a proper fix for my reported issue, and I believe
there may be more underlying issue in the dependency tracking part of phi-of-ops
optimization. In order to avoid miscompiling unknown user program, we disabled it in #1204.
We need to further understand the phi-of-ops optimization and fix the outstanding issues of NewGVN in llvm Bugzilla to reenable this optimization for llpc.

**Comment by jayfoad** [comment]
Looks like https://bugs.llvm.org/show_bug.cgi?id=49873 is fixed upstream now?
