### ISSUE TITLE
`lgc/patch/PatchImageOpCollect.cpp` fails to build

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1252]
The `PatchImageOpCollect` pass introduced by the latest merge (https://github.com/GPUOpen-Drivers/llpc/commit/e3ecd451f04d878965901b2fd508dcdacd345022) fails to build:
```
llpc/lgc/patch/PatchImageOpCollect.cpp:82:19: error: no member named 'useImageOp' in 'lgc::ResourceUsage'; did you mean 'useImages'?
        resUsage->useImageOp = true;
                  ^~~~~~~~~~
                  useImages
llpc/lgc/include/lgc/state/ResourceUsage.h:154:8: note: 'useImages' declared here
  bool useImages = false;                  // Whether images are used
       ^
llpc/lgc/patch/PatchImageOpCollect.cpp:93:1: error: out-of-line definition of 'initializePatchImageOpCollectPass' does not match any declaration in namespace 'llvm'; did you mean 'initializePatchResourceCollectPass'?
INITIALIZE_PASS(PatchImageOpCollect, DEBUG_TYPE, "Patch LLVM for image operation collecting", false, false)
^
llvm/include/llvm/PassSupport.h:46:14: note: expanded from macro 'INITIALIZE_PASS'
  void llvm::initialize##passName##Pass(PassRegistry &Registry) {              \
             ^
<scratch space>:30:1: note: expanded from here
initializePatchImageOpCollectPass
^
llpc/lgc/include/lgc/patch/Patch.h:60:6: note: 'initializePatchResourceCollectPass' declared here
void initializePatchResourceCollectPass(PassRegistry &);
     ^
2 errors generated.
```

I think this is not an issue caught by our CI because the cmake file with all patch passes has not yet been updated to include it: https://github.com/GPUOpen-Drivers/llpc/blob/e3ecd451f04d878965901b2fd508dcdacd345022/lgc/CMakeLists.txt#L130

**Comment by amdrexu** [comment]
@kuhar Thanks for reporting this. We will look into the issue.

**Comment by AMD-dwang** [comment]
llpc/lgc/patch/PatchImageOpCollect.cpp is not added to CMakeLists.txt, Why is it compiled?

**Comment by kuhar** [comment]
> llpc/lgc/patch/PatchImageOpCollect.cpp is not added to CMakeLists.txt, Why is it compiled?

It's compiled in our internal builds because we `glob` all sources in this directory, and we can of course just exclude it from being build.
I opened an issue because it's unexpected to me to have source files in the tree that are broken, and it seemed like a bug/oversight to me.

**Comment by kuhar** [comment]
I think these two file should be either fixed and included in the cmake lists, or removed until they are ready to be used.

**Comment by AMD-dwang** [comment]
Thanks for your explanation. It makes more sense for us to remove them.
