### ISSUE TITLE
Relocation on undefined symbol

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#1366]
We are seeing errors caused by LLPC generating an elf file with a relocation on the symbol `lds`, but that symbol is undefined in the symbol table.  Here is a reduced example: [t.spvasm.txt](https://github.com/GPUOpen-Drivers/llpc/files/7016646/t.spvasm.txt)

To see the problem run:

```
spirv-as t.spvasm.txt -o t.spv --target-env spv1.3
amdllpc -gfxip=9 t.spv -o t.elf
llvm-objdump t.elf -rt
```

The output that I see is:

```
$ llvm-objdump t.elf -rt

t.elf:  file format elf64-amdgpu

SYMBOL TABLE:
0000000000000024 l       .text  0000000000000000 BB0_1
0000000000000000 g     F .text  0000000000000058 _amdgpu_cs_main
0000000000000000         *UND*  0000000000000000 lds

RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE                     VALUE
0000000000000008 R_AMDGPU_GOTPCREL32_LO   lds
0000000000000010 R_AMDGPU_GOTPCREL32_HI   lds
```

**Comment by s-perron** [comment]
@xuechen417 I believe this regression was caused by https://github.com/GPUOpen-Drivers/llpc/pull/1303.

**Comment by jinjianrong** [comment]
@s-perron could the issue be fixed  by https://github.com/GPUOpen-Drivers/llpc/pull/1359?

**Comment by s-perron** [comment]
Yes that fixes the issue thanks.
