### ISSUE TITLE
`vkgcDefs.h` does not check returned `Result`s

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1472]
I annotated functions returning `Result` to illustrate the issue:

```
/ssd/opensource/amdvlk/vulkandriver/drivers/llpc/llpc/include/../../include/vkgcDefs.h:1148:7: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunus
ed-result]
      m_pCache->SetValue(m_rawHandle, false, nullptr, 0);
      ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

`Result`s should either be checked or the return type should be changed.

**Comment by xuechen417** [comment]
@kuhar How can I reproduce the warnings in local build? What's the compiling options?

**Comment by kuhar** [comment]
> @kuhar How can I reproduce the warnings in local build? What's the compiling options?

The warning itself it not the issue. The issue is that `m_pCache->SetValue` returns `Results`, but this result is ignored in `Put`:
```
  virtual Result SetValue(RawEntryHandle rawHandle, bool success, const void *pData, size_t dataLen) = 0;
```

```
  void Put() {
    if (!m_pCache)
      return;
    if (m_mustPopulate)
      m_pCache->SetValue(m_rawHandle, false, nullptr, 0);
    m_pCache->ReleaseEntry(m_rawHandle);
```

To get the same warning as I did, you can add  `[[clang::warn_unused_result]]` in front of the `SetValue` function declaration.

**Comment by kuhar** [comment]
Also, this is described in depth in the `[RFC] Improving LLPC Result checking` thread on our mailing list that I started.
