### ISSUE TITLE
[CI] Fix clang-tidy member variable naming check

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1494]
The check suggests something that I think is not in line with our coding style:
```
/vulkandriver/drivers/llpc/llpc/context/llpcShaderCache.h:176:16: warning: invalid case style for constant member 'm_readOnlyLock' [readability-identifier-naming]
    const bool m_readOnlyLock;
               ^~~~~~~~~~~~~~
               MReadOnlyLock
```

Sample run: https://github.com/GPUOpen-Drivers/llpc/runs/4096860724?check_suite_focus=true.

**Comment by Flakebi** [comment]
In the clang tidy config, members should have a `m_` prefix, but public members, class constants (`static const`) and constant members (`const`) do not.

From the coding standard:

> - A non-public member variable should be named like a variable, but with an extra m_ prefix (unlike LLVM style, but like PAL style, and like LLDB and WebKit).
> …
> - A constant (technically a static variable or class/struct member variable, but final so it is used like a constant) should be in CamelCase.

So I guess we should have a `m_` prefix for `const` members, but not for `static const` members?

Looking at how it’s currently done, all non-public `const` members have a `m_` prefix.

**Comment by kuhar** [comment]
Can't we use `m_` for everything? I don't really care that much, it's just something I haven't seen in the part of LLVM and LLPC that I touch.

**Comment by kuhar** [comment]
Feel free to close this if this is as intended.

**Comment by kuhar** [comment]
> Feel free to close this if this is as intended.

To clarify, I thought that we should use `MReadOnlyLock` instead of `m_readOnlyLock`, and I thought that `MReadOnlyLock` looked weird. However, now I understand that the coding style suggests `ReadOnlyLock`, which is much more reasonable and clang-tidy does not complain about it.

So it's just confusion on my end caused by the way clang-tidy suggested to fix it.

**Comment by Flakebi** [comment]
@amdrexu, what is the desired coding style for private, const member variables?
Should it be (the current practice)
```c++
class C {
	const bool m_readOnlyLock;
};
```

or (the current style enforced by clang-tidy)
```c++
class C {
	const bool ReadOnlyLock;
};
```

**Comment by amdrexu** [comment]
We stick to this style
class C {
	const bool m_readOnlyLock;
};

Unless this is a static const member
class C {
	static const bool ReadOnlyLock;
};
