### ISSUE TITLE
Does llpc support compile "OpenGL ES" shader

### ISSUE THREAD

**Issue by xiaoqiang-wang** [GPUOpen-Drivers/llpc#1534]
Hello, my friend, 
I want to use llpc compile OpenGL ES shader program , but it report an error. 
#### The Eerror message is below, it seems llpc do not support "OpenGL ES" shader
```
// GLSL program compile/link log
ERROR: Fail to compile GLSL sources

Compiling vertex stage:
ERROR: #version: ES shaders for SPIR-V require version 310 or higher
ERROR: ./temp_shader.vert:18: 'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan
ERROR: ./temp_shader.vert:18: '' : missing #endif
ERROR: 3 compilation errors.  No code generated.
```

#### Q3. Does there any tools to do  "OpenGL ES" -> "OpenGL " convert?   I have too much  shader to compile, I can't to do  convert manually.

Below is my shader program
```
#version 300 es
#define SHADOW_MAP
#define SOFT_SHADOW
#define SV_30
#ifdef GL_ES
precision highp float;
#endif
#ifndef GL_ES
#define highp
#define mediump
#define lowp
#endif
#ifdef USE_UBOs
	#include cameraConsts;
	#include meshConsts;
	#include staticMeshConsts;
#else
	uniform highp mat4 mvp;
	uniform highp mat4 mv;
	uniform highp mat4 model;
	uniform highp vec3 view_pos;
#endif

in vec3 in_position;
in vec2 in_texcoord0;

#ifdef INSTANCING
//in mat4 in_instance_mv;
in vec4 in_instance_mv0;
in vec4 in_instance_mv1;
in vec4 in_instance_mv2;
in vec4 in_instance_mv3;

in mat4 in_instance_inv_mv;
#endif
	
out vec2 out_texcoord0;


void main()
{    
	vec3 up; 
	vec3 right;
	vec3 fwd;

#ifdef INSTANCING
	mat4 in_instance_mv = mat4(in_instance_mv0, in_instance_mv1, in_instance_mv2, in_instance_mv3);
#endif
	
#ifdef AALIGNED	
	up = vec3( 0.0, 1.0, 0.0);
#else
	up = vec3( mv[0][1], mv[1][1], mv[2][1]);
#endif

	right = vec3( mv[0][0], mv[1][0], mv[2][0]);
	
#ifdef USE_UBOs
	vec3 delta = vec3( model[3][0], model[3][1], model[3][2]) - view_posXYZ_normalized_time.xyz;
#else
	vec3 delta = vec3( model[3][0], model[3][1], model[3][2]) - view_pos;
#endif
	delta = normalize( delta);

	vec3 position = in_position.x * right + in_position.y * up + in_position.z * delta;

#ifdef INSTANCING
    mat4 mvp2 = mvp * in_instance_mv;

	gl_Position = mvp2 * vec4( position, 1.0);
#else
	gl_Position = mvp * vec4( position, 1.0);
#endif

	out_texcoord0 = in_texcoord0;
}


```

**Comment by amdrexu** [comment]
Hello, We don't support OpenGL shader (both desktop version or ES version). Only Vulkan shader is supported.

**Comment by xiaoqiang-wang** [comment]
😀 
Thanks for your reply very much  my friend,

##### 1. I tried glslangValidator,  but it  not support  convert OpenGL ES shader to SPIR-V either.
##### 2.  It seems the best way do "OpenGL ES ->OpenGL " convert  is mannully change the source file 😓...

**Comment by piotrAMD** [comment]
glslangValidator does support OpenGL ES -> SPIR-V conversion, but it requires OpenGL ES version 3.1, so you need use `#version 310 es` declaration on top. 

Looking at your shader, you also need to do two more modifications:
- Move the standalone uniform declarations into a single block with explicit `binding`.
- Add explicit `location` for each `in` and `out` variable (or use `--auto-map-locations` option).

**Comment by xiaoqiang-wang** [comment]
@piotrAMD  my friend,
😃  Thanks for your kindly reply very much.

Besides above shader,  there are still 2000+ shaders  need to change mannully...
