### ISSUE TITLE
amdllpc does not pick up spvgen when compiled with TSan enabled

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1540]
When I build amdllpc with TSan enabled, the build succeeds but amdllpc can't find spvgen in the spvgen directory. I confirmed that `spvgen.so` is there and has the expected modification time. When I replace this spvgen with one compiled without TSan, it gets loaded as expected and works fine.

My cmake invocation is something like:
```
cmake ../../ -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug -GNinja \
    -DXGL_BUILD_TESTS=ON -DXGL_BUILD_CACHE_CREATOR=ON \
    -DLLPC_ENABLE_SHADER_CACHE=ON -DXGL_USE_SANITIZER=Thread \
    -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
```

The amdllpc error  is:
```
ERROR: Failed to load SPVGEN from specified directory
```

**Comment by Sisyph** [comment]
It could be failing to find the sanitizer runtime library SPVGEN needs to link against. Try ldd on spvgen.so to see if its a dependency? If that's the case, you can add the sanitizer runtime to your library path, or 
@Flakebi suggested LD_PRELOAD=$(clang -print-file-name=libclang_rt.asan-x86_64.so)

**Comment by kuhar** [comment]
I did a fresh build and it's working without `LD_PRELOAD` or other changes. I think the issue might have been that I use the [mold linker](https://github.com/rui314/mold) in my previous experiment, and it's definitely not a mature piece of software. It works fine with lld.
