### ISSUE TITLE
[CI] GCloud warns about authentication method deprecation 

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1569]
> "service_account_key" has been deprecated. Please switch to using google-github-actions/auth which supports both Workload Identity Federation and Service Account Key JSON authentication. For more details, see https://github.com/google-github-actions/setup-gcloud#authorization

Sample run: https://github.com/GPUOpen-Drivers/llpc/runs/4430004534?check_suite_focus=true#step:4:9

**Comment by SwarzChen** [comment]
I encountered the same warning...
