### ISSUE TITLE
Add LIT test for pervertex input variable

### ISSUE THREAD

**Issue by AMD-dwang** [GPUOpen-Drivers/llpc#1576]
Pervertex input variable is new feature, currently we have no LIT test for it. When it is released, we should add test to prevent future regressions.  Relevant PR: https://github.com/GPUOpen-Drivers/llpc/pull/1555

**Comment by kuhar** [comment]
Ping. Is there any progress on this?

**Comment by AMD-dwang** [comment]
It was not released. I'll add it once it's published. thanks.

**Comment by AMD-dwang** [comment]
https://github.com/GPUOpen-Drivers/llpc/pull/1723.
Add a new test for per-vertex input data.
