### ISSUE TITLE
Check if the GLSL file extensions unit tests needs copyright notice

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1580]
The latest import (#1578) added a copyright header in the middle of a unit test tile. The test `TEST(InputUtilsTest, IsGlslShaderFile)` in `llpc/unittests/standaloneCompiler/testInputUtils.cpp` references an external website for the list of GLSL shader file extensions but does not duplicate/reference any external implementation or code.

The task is to confirm if the test needs the copyright notice and either explain why it does in a comment or remove the comment with the notice.

**Comment by kuhar** [comment]
cc @jinjianrong

**Comment by jinjianrong** [comment]
if any information from the website is referenced, we need to add the copyright notice per our legal's request.
