### ISSUE TITLE
llpc fails to build with g++ 

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1645]
These failures first started occurring 3 days ago: https://github.com/GPUOpen-Drivers/llpc/runs/4811031868?check_suite_focus=true#step:8:1928.

The error message happens when building `llvm-tblgen`:
```
/usr/bin/ld: --color-diagnostics: unknown option
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
```

The time of the first failure lines up with the last llvm-project import: https://github.com/GPUOpen-Drivers/llvm-project/commit/c20ba7614ecdc78b3d99601423783100835200c1

**Comment by kuhar** [comment]
+cc: @JaxLinAMD @amdrexu @Flakebi @dstutt

**Comment by Flakebi** [comment]
I bisected the failure to [D116521](https://reviews.llvm.org/D116521) (commit https://github.com/llvm/llvm-project/commit/44e3365775101fec3fd355eda339282258d74415).

**Comment by Flakebi** [comment]
I bisected further. The cause for the compilation failure is that a new `CMAKE_MODULE_PATH` was added (https://github.com/llvm/llvm-project/commit/44e3365775101fec3fd355eda339282258d74415#diff-f6c3fac0de0e2bbd79ac93b0a6aabe77d9961c5487347a2170c78ac77770d8afR209)
and it overwrites the `llvm_check_linker_flag` function from `llvm/cmake/modules/LLVMCheckLinkerFlag.cmake`, reimplementing it as `CheckCompilerFlag`. Removing `cmake/Modules/CheckLinkerFlag.cmake` gets rid of the overwriting function and makes it compile again for me.

**Comment by kuhar** [comment]
Given that this is still in review upstream, and once it lands we will additional wait time for a submodule bump, should we temporarily disable gcc builds?

WDYT @Flakebi @vettoreldaniele?

**Comment by vettoreldaniele** [comment]
Disabling gcc until it works again sounds good to me.

**Comment by Flakebi** [comment]
Sounds good to me too

**Comment by kuhar** [comment]
OK, I'll prepare a PR

**Comment by kuhar** [comment]
@Flakebi Do we have any news on this? I can see that https://reviews.llvm.org/D117537 was submitted 2 weeks ago.

**Comment by Flakebi** [comment]
Thanks, I missed that it got submitted
