### ISSUE TITLE
Toolchain upgrade broke coverage builds

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1771]
The most recent toolchain upgrade broke coverage builds: https://github.com/GPUOpen-Drivers/llpc/runs/5868011955?check_suite_focus=true.

**Comment by kuhar** [comment]
cc @vettoreldaniele

**Comment by vettoreldaniele** [comment]
In the meantime, we should mitigate this and revert the toolchain change, otherwise we're going to run into serious delays with the CI. The toolchain update can be later tested on a private fork by running the `Build AMDVLK` action once we have a solution.

**Comment by kuhar** [comment]
A middle ground would be keeping clang-tidy at 12 and downgrading the other components back to 11. @Flakebi, could you take care of this?

**Comment by Flakebi** [comment]
I agree with Jakub that high memory usage is probably an issue. The coverage docker container built fine for me locally, but I suspect that it used quite a bit of memory because something killed a VM that was running in parallel.

**Comment by Flakebi** [comment]
Docker just failed with exit code 1 for me locally because https://gerrit.googlesource.com/git-repo/ was not reachable (already had a similar failure when downloading repo for something else today). That could explain the other failure @vettoreldaniele  saw.
