### ISSUE TITLE
Build options required for check-amdllpc appear to be undocumented

### ISSUE THREAD

**Issue by perlfu** [GPUOpen-Drivers/llpc#1826]
Documentation describes using check-amdllpc to run LIT tests, but check-amdllpc target is unavailable in Release and Debug builds.
check-amdllpc target requires some combination of the following cmake flags:
- -DXGL_BUILD_TESTS=1
- -DXGL_BUILD_LIT=1
- -DLLPC_BUILD_TESTS=1
- -DLLPC_BUILD_LIT=1
- -DLLPC_BUILD_LLVM_TOOLS=1
- -DLLVM_INCLUDE_TESTS=ON

However I am not entirely clear on which are required because the cmake file describes some as deprecated, but the check-amdllpc is unavailable without them.

**Comment by amdrexu** [comment]
Not sure if Jakub has time to clarify the build and usage of unit tests. We do encounter issues if someone doesn't get familiar with googletest framework.

**Comment by kuhar** [comment]
Thanks for bringing this up, I'll update the documentation. I also think it should be safe to remove the deprecated flags, they've been marked as such for close to a year now.

FYI, in case someone needs this urgently: it's best to use the [same flags as the CI](https://github.com/GPUOpen-Drivers/llpc/blob/dev/docker/amdvlk.Dockerfile#L118) when in doubt.

**Comment by kuhar** [comment]
I opened 3 PRs (against LLPC, XGL, and AMDVLK). Please take a look.

**Comment by dstutt** [comment]
Thanks for doing this. I've reviewed the 3 changes (and re-triggered the internal builds - there was an issue with one of the systems that caused a failure on one platform).
Do you think we should document the LLPC_BUILD_TESTS option somewhere too?

**Comment by kuhar** [comment]
I don't think you need to ever set `LLPC_BUILD_TESTS` manually. The only thing that comes to mind would be standalone LLPC builds, but I'd have to confirm.
