### ISSUE TITLE
Code traceability strategies

### ISSUE THREAD

**Issue by Ibnmardanis24** [GPUOpen-Drivers/llpc#1871]
This issue would like to raise 3 main points derived from my brief experience toying around with the compiler:

- I feel that optimization features should be off by default. Choosing to apply optimizations should be an **active** selection from the end-user, rather than the opposite.
- Even after setting off every opt option I could find, the _-dump-pass-name_ flag reveals that around 200 passes are still applicable. I was wondering whether any of these could be further removed when in a no optimization scenario. My goal is to find the "most reduced subset" of compiler passes capable of bringing a particular shader from SPIR-V to a valid and representative AMD GCN kernel. In order to be more specific, I am particularly concerned with **compute** shaders and their offline pipelines.
- Finally, my end interest is on developing tracing and debugging strategies using this compiler as sandbox. Any and all tools already present in this project, even unfinished ones, are interesting for me to learn and understand.

I am sorry if this was not the right forum for such requests, but I could not find any alternatives...

**Comment by Flakebi** [comment]
Vulkan expects the default to be optimized and as llpc is the compiler frontend for Vulkan, it’s following that :)

The `amdllpc` offline compiler supports command line options to disable optimizations, like `-llpc-opt=quick` (equivalent of -O1, there’s also `-llpc-opt=none`, though beware that this is untested and sometimes creates buggy code).
And, from the Vulkan API, one can set `VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT` to disable most optimizations.

**Comment by Ibnmardanis24** [comment]
Interesting points.

Following on your comment, 

> Vulkan expects the default to be optimized and as llpc is the compiler frontend for Vulkan, it’s following that :)

In what sense does Vulkan require optimized shaders as input? Better even, where in the standards is this specified? 

Coming from an entirely different background this seems really weird to me, any reference to the docs is appreciated!

> The `amdllpc` offline compiler supports command line options to disable optimizations, like `-llpc-opt=quick` (equivalent of -O1, there’s also `-llpc-opt=none`, though beware that this is untested and sometimes creates buggy code).

These are the kind of options I was mentioning on my first post (I believe there is also a `-opt=none` that is passed to LLVM). I suppose you left the none selection untested because of this Vulkan interaction. However, wouldn't it be easier to test the offline compiler without optimizations than having a big pile of transformations for testing? In any case, this maybe interesting anyway, what would it take to create confidence around the compiler's non-optimizing version?

**Comment by Flakebi** [comment]
> My interest is not being fast, but rather, being always correct.

I agree with that, `-O0` not working is a bug. To add some context, there were llvm (amdgpu backend) bugs with `-O0`. Some of them were fixed but I think nobody did enough testing to be confident that there are no more of these bugs.
Which smoothly leads to your next question

> How are you testing the compiler under optimizing settings?

For Vulkan, that is running the [Conformance Test Suite](https://github.com/KhronosGroup/VK-GL-CTS/tree/main/external/vulkancts) (and some additional testing internally at AMD).
So, a passing CTS when forcing `-O0` would be nice. It just needs someone doing the work ;)
