### ISSUE TITLE
dEQP-VK.graphicsfuzz.call-if-while-switch

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#203]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[call-if-while-switch.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609582/call-if-while-switch.zip)

**Comment by amdrexu** [comment]
Are those issues urgent for you? We need to know the priority.

**Comment by paulthomson** [comment]
These are not urgent. Thanks.

**Comment by amdrexu** [comment]
Thank you for feedbacks. We will arrange resources to handle those issues.

**Comment by jinjianrong** [comment]
@paulthomson 
Paul, would you like to take the ownership to fix these issues?

**Comment by amdrexu** [comment]
I will assign those issues to developers. If someone else believes he can handle this, feel free to reassign it to yourself and make comments in the issue ticket.

**Comment by dnovillo** [comment]
@jinjianrong I will assign them to myself for now.  I will re-assign as folks start working on them internally.

**Comment by dnovillo** [comment]
@jinjianrong 

We will need access to this repository.  I am not allowed to assign issue to me at the moment.  How do we get access?  Thanks.

**Comment by kuhar** [comment]
This issue is fixed and can be closed.
