### ISSUE TITLE
dEQP-VK.graphicsfuzz.control-flow-in-function

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#205]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[control-flow-in-function.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609619/control-flow-in-function.zip)

**Comment by jaebaek** [comment]
I built it in Release 64bit mode based on [AMDVLK](https://github.com/GPUOpen-Drivers/AMDVLK#64-bit-build) and [spvgen](https://github.com/GPUOpen-Drivers/spvgen#how-to-build), but I cannot reproduce this bug.

Did someone fix this already?

**Comment by paulthomson** [comment]
I used a Debug release.

**Comment by amdrexu** [comment]
To reproduce this issue, a debug version of AMDLLPC might be required.

**Comment by jaebaek** [comment]
Yes, I can reproduce it with the debug build. Thank for you doublechecking it.
I am investigating this issue now.

**Comment by jaebaek** [comment]
Sorry. I spent some time but I do not understand it. It is complicated. Let me unassign me for now.

**Comment by paulthomson** [comment]
Appears to be fixed!
