### ISSUE TITLE
dEQP-VK.graphicsfuzz.discard-continue-return

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#206]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[discard-continue-return.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609715/discard-continue-return.zip)

**Comment by kuhar** [comment]
I can't reproduce this bug on master nor dev (debug build).

**Comment by paulthomson** [comment]
Hmm this still fails for me. Here is what I did.

In a AMDVLK directory:

```sh
curl https://storage.googleapis.com/git-repo-downloads/repo >repo
chmod a+x repo
mkdir vulkandriver
cd vulkandriver
# can also try -b master
../repo init -u https://github.com/GPUOpen-Drivers/AMDVLK.git -b dev
../repo sync
cd drivers/xgl
cmake -H. -Bbuilds/Release64 -DCMAKE_BUILD_TYPE=Debug
cd builds/Release64
make -j$(nproc) amdllpc
(cd ../../../spvgen/external && rm -rf glslang/ SPIRV-Tools/ && python fetch_external_sources.py)
make -j$(nproc) spvgen
```

After extracting the attached SPIR-V shader somewhere:

```sh
export PATH=/path/to/AMDVLK/vulkandriver/drivers/xgl/builds/Release64/llpc:$PATH
export LD_LIBRARY_PATH=/path/to/AMDVLK/vulkandriver/drivers/xgl/builds/Release64/spvgen:$LD_LIBRARY_PATH

$ amdllpc -gfxip=9.0.0 -verify-ir -o temp.out discard-continue-return.variant_fragment_shader.frag.spv 
ERROR: Fails to validate SPIR-V: 
error: 67: block <ID> 34[%34] exits the selection headed by <ID> 35[%35], but not via a structured exit
  %34 = OpLabel


ERROR: 
=====  AMDLLPC FAILED  =====
```

**Comment by paulthomson** [comment]
I am guess updating to a newer SPIR-V validator may fix this. Or perhaps I am somehow stuck with an old, stale version in my build.

**Comment by amdrexu** [comment]
If this error is caused by SPIR-V validation. You can build a spirv-val.exe from the repo: https://github.com/KhronosGroup/spirv-tools. If newer version fixes it, then it is caused by old validation rules.
If you want to continue to look into the failure other than SPIR-V validation, you can add this option when using AMDLLPC: --val=false. This will turn off SPIR-V validation.

**Comment by paulthomson** [comment]
Thanks! I may add this to my testing command, although perhaps it is useful to find these "bugs" so that they can be "fixed" by updating SPIRV-Tools.

**Comment by paulthomson** [comment]
I confirm that a newer build does not fail validation.

**Comment by paulthomson** [comment]
With `-val=false`, the shader does indeed compile successfully. So the only fix needed is to update SPIRV-Tools.

**Comment by amdrexu** [comment]
Thanks for feedbacks. We will update SPVGEN.

**Comment by paulthomson** [comment]
This still seems to fail.

**Comment by jinjianrong** [comment]
Please re-open the issue if the issue is still there
