### ISSUE TITLE
dEQP-VK.graphicsfuzz.loop-dead-if-loop

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#207]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[loop-dead-if-loop.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609716/loop-dead-if-loop.zip)

**Comment by jaebaek** [comment]
I built it in Release 64bit mode based on [AMDVLK](https://github.com/GPUOpen-Drivers/AMDVLK#64-bit-build) and [spvgen](https://github.com/GPUOpen-Drivers/spvgen#how-to-build), but I cannot reproduce this bug.

Did someone fix this already?

**Comment by paulthomson** [comment]
I used a Debug release.

**Comment by kuhar** [comment]
I can reproduce in Debug mode on the master branch. Looking into it.

**Comment by kuhar** [comment]
I submitted an LLVM commit fixing the issue here: https://reviews.llvm.org/D67974

**Comment by kuhar** [comment]
The fix was committed in https://reviews.llvm.org/rL372874.

**Comment by kuhar** [comment]
After doing some cleanup in LLVM when working on this issue, a new issue with MachineDominators surfaced: PHIElimination lied about preserving MDT. I submitted a fix here: https://reviews.llvm.org/D68154
Not sure if the AMDGPU target uses this part of the machine pass pipeline, but may be work merging in this fix too.

**Comment by kuhar** [comment]
The Machine (Post)Dominators should be fully fixed now by the series of LLVM commits:

1. https://reviews.llvm.org/rL373341 : [Dominators][CodeGen] Add MachinePostDominatorTree verification.
2. https://reviews.llvm.org/rL373376 : Reapply [Dominators][CodeGen] Clean up MachineDominators.
3. https://reviews.llvm.org/rL373377 : [Dominators][CodeGen] Fix MachineDominatorTree preservation in PHIElimination.
4. https://reviews.llvm.org/rL373378 : [Dominators][CodeGen] Don't mark MachineDominatorTree as preserved in MachineLICM.
5. https://reviews.llvm.org/rL373382 : Add a missing pass in ARM O3 pipeline.

**Comment by paulthomson** [comment]
Appears to be fixed!
