### ISSUE TITLE
dEQP-VK.graphicsfuzz.loop-nested-ifs

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#208]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[loop-nested-ifs.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609719/loop-nested-ifs.zip)

**Comment by MarcinKantochAMD** [comment]
I can't reproduce the issue with our LLPC stack.

**Comment by paulthomson** [comment]
This still fails for me. Are you using a 64 bit debug build of the dev branch?

**Comment by paulthomson** [comment]
```
amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv
PHI node has multiple entries for the same basic block with different incoming values!
  %__llpc_output_proxy_.4.0 = phi float [ %34, %25 ], [ %33, %25 ], [ %40, %35 ], [ 1.000000e+00, %41 ]
label %25
  %33 = extractelement <4 x float> %spec.select, i32 0
  %34 = extractelement <4 x float> %spec.select, i32 0
in function llpc.shader.FS.main
ERROR: LLVM FATAL ERROR:Broken function found, compilation aborted!
```

**Comment by kuhar** [comment]
I can reproduce it on master in Debug mode.

**Comment by MarcinKantochAMD** [comment]
Sorry Paul. I was not aware that your issues relate to Debug build. I was testing with a Release build.

**Comment by paulthomson** [comment]
Yes, sorry I should have made this clearer.

**Comment by kuhar** [comment]
This issue is fixed and can be closed.

**Comment by paulthomson** [comment]
Appears to be fixed!
