### ISSUE TITLE
dEQP-VK.graphicsfuzz.loops-ifs-continues-call

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#209]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[loops-ifs-continues-call.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609722/loops-ifs-continues-call.zip)

**Comment by MarcinKantochAMD** [comment]
I can't find this test yet available. Can you verify Paul that the name is correct.

**Comment by MarcinKantochAMD** [comment]
Sorry Paul. I was not aware that your issues relate to Debug build. I was testing with a Release build.

**Comment by paulthomson** [comment]
Some of the tests are still pending CLs but the AmberScript file and the SPIR-V shader is attached.

**Comment by jaebaek** [comment]
Sent a PR: https://reviews.llvm.org/D68032

**Comment by jaebaek** [comment]
The PR was merged: https://github.com/llvm/llvm-project/commit/d98cb81cd11c8a4d7017c4820cae202d31d757bb

**Comment by paulthomson** [comment]
Appears to be fixed!
