### ISSUE TITLE
dEQP-VK.graphicsfuzz.max-mix-conditional-discard

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#210]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[max-mix-conditional-discard.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609724/max-mix-conditional-discard.zip)

**Comment by MarcinKantochAMD** [comment]
I tested today and the test is passing on our LLPC stack.

**Comment by MarcinKantochAMD** [comment]
Sorry Paul. I was not aware that your issues relate to Debug build. I was testing with a Release build.

**Comment by kuhar** [comment]
LLPC fails in `SIInstrInfo.cpp:3197` when verifying the following instruction:
```
bb.4 (%ir-block.34):
; predecessors: %bb.1
  successors: %bb.5(0x40000000), %bb.6(0x40000000); %bb.5(50.00%), %bb.6(50.00%)

  S_CMPK_GT_I32 8, 179, implicit-def $scc       ;  <=== 
  S_CBRANCH_SCC1 %bb.6, implicit killed $scc
$3 = void
```

The diagnostic message is for the 0th operand and says:
`Illegal immediate value for operand.`

I don't understand MIR to tell what the issue is here.

**Comment by paulthomson** [comment]
Appears to be fixed!
