### ISSUE TITLE
dEQP-VK.graphicsfuzz.mix-floor-add

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#211]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[mix-floor-add.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609727/mix-floor-add.zip)

**Comment by amdrexu** [comment]
The addend is from a integer bit-cast with the value of <i32 38730, i32 63193, i32 63173>. This value is finally converted to denormals and LLVM applies constant folding for fmuladd, which causes a assert. Will further determine how to fix.

**Comment by MarcinKantochAMD** [comment]
I tested today and the test is passing on LLPC stack. Does it fail or throw an assert? I am testing with a release build.

**Comment by MarcinKantochAMD** [comment]
Sorry Paul. I was not aware that your issues relate to Debug build. I was testing with a Release build.

**Comment by paulthomson** [comment]
This still seems to fail.

**Comment by jayfoad** [comment]
This is a bug in the LLVM floating point emulation code. I've raised it upstream: https://bugs.llvm.org/show_bug.cgi?id=44010

**Comment by jayfoad** [comment]
There's a fix in upstream review: https://reviews.llvm.org/D69772

**Comment by jayfoad** [comment]
Fixed in GPUOpen-Drivers/llvm-project@e62555c129d535d524354351791c5474c9929582.
