### ISSUE TITLE
dEQP-VK.graphicsfuzz.modf-gl-color

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#212]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[modf-gl-color.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609729/modf-gl-color.zip)

**Comment by jaebaek** [comment]
I cannot reproduce the failure. I want to doublecheck if this is already fixed.

**Comment by paulthomson** [comment]
I used a Debug release.

**Comment by MarcinKantochAMD** [comment]
I ran the test today and it is passing on our LLPC stack.

**Comment by MarcinKantochAMD** [comment]
Sorry Paul. I was not aware that your issues relate to Debug build. I was testing with a Release build.

**Comment by paulthomson** [comment]
Appears to be fixed!
