### ISSUE TITLE
dEQP-VK.graphicsfuzz.two-loops-matrix

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#215]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[two-loops-matrix.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609738/two-loops-matrix.zip)

**Comment by kuhar** [comment]
This fails in llpcCompiler.cpp:220:
```
class LlpcDiagnosticHandler : public llvm::DiagnosticHandler
{
    bool handleDiagnostics(const DiagnosticInfo& diagInfo) override
    {
        if (EnableOuts() || EnableErrs())
        {
            if ((diagInfo.getSeverity() == DS_Error) || (diagInfo.getSeverity() == DS_Warning))
            {
                DiagnosticPrinterRawOStream printStream(outs());
                printStream << "ERROR: LLVM DIAGNOSIS INFO: ";
                diagInfo.print(printStream);
                printStream << "\n";
                outs().flush();
            }
           ...
        }
==>     LLPC_ASSERT(diagInfo.getSeverity() != DS_Error);
        return true;
    }
};
```
With the error message: `unsupported dynamic alloca`.
Not sure what the intention was here -- perhaps to emit diagnostics and terminate on `DS_Error`s? In that case, I'd expect to see something like `llvm::report_fatal_error` used instead of the assertion.

Similar applied to issue #214.

**Comment by linqun** [comment]
please check whether there are some alloca in the middle of function. if yes, please try to find which pass add it and try to move it to the begin of function.

**Comment by MarcinKantochAMD** [comment]
Hi Paul. I tested today and can't reproduce the issue anymore.

**Comment by MarcinKantochAMD** [comment]
Sorry Paul. I was not aware that your issues relate to Debug build. I was testing with a Release build.

**Comment by kuhar** [comment]
This issue is fixed and can be closed.

**Comment by paulthomson** [comment]
Appears to be fixed!
