### ISSUE TITLE
dEQP-VK.graphicsfuzz.two-loops-set-struct

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#216]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[two-loops-set-struct.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609739/two-loops-set-struct.zip)

**Comment by jaebaek** [comment]
I cannot reproduce the failure. I want to doublecheck if this is already fixed.

**Comment by paulthomson** [comment]
I used a Debug release.

**Comment by MarcinKantochAMD** [comment]
Hi Paul. I tested today and can't reproduce the issue.

**Comment by MarcinKantochAMD** [comment]
Sorry Paul. I was not aware that your issues relate to Debug build. I was testing with a Release build.

**Comment by paulthomson** [comment]
Appears to be fixed!
