### ISSUE TITLE
dEQP-VK.graphicsfuzz.two-loops-with-break

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#217]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[two-loops-with-break.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609743/two-loops-with-break.zip)

**Comment by kuhar** [comment]
This seems to a BB iterator invalidation bug in LLVM's FlattenCFG pass. The code is unchanged in ToT LLVM. I'll look further into this, try to reproduce it in LLVM, and report back.

**Comment by kuhar** [comment]
I reproduced it in the ToT LLVM and submitted a patch for review here: https://reviews.llvm.org/D67672

**Comment by kuhar** [comment]
The fix was committed in https://reviews.llvm.org/rL372347 and should resolve the issue after updating LLVM.

**Comment by paulthomson** [comment]
Appears to be fixed!
