### ISSUE TITLE
Inconsistent use of  LLPC_CLIENT_INTERFACE_MAJOR_VERSION

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#251]
The `entryStage` member of the `PipelineShaderInfo` struct is only defined if `LLPC_CLIENT_INTERFACE_MAJOR_VERSION >= 21`.  See [here](https://github.com/GPUOpen-Drivers/llpc/blob/b088b87ee23740e16301444d85ec0e9921504a8a/include/llpc.h#L365).

However, not all uses of it are guarded by that macro.  See [here](https://github.com/GPUOpen-Drivers/llpc/blob/dev/context/llpcCompiler.cpp#L846).

**Comment by linqun** [comment]
Yes, it is our fault. we will fix it ASAP.
