### ISSUE TITLE
Deprecate pre-GFX10 support in LLPC

### ISSUE THREAD

**Issue by amdrexu** [GPUOpen-Drivers/llpc#2711]
Since PAL removed pre-GFX10 support, we decide to follow the same strategy by removing all pre-GFX10 codes in LLPC. Will start this work in the upcoming weeks.

**Comment by Triang3l** [comment]
And I was thinking about using LLVM on GFX4/GFX5, but I couldn't even find the intrinsic for vertex fetch (let alone one with `ALT_CONST` so I could share the binding for reading from the ring buffer between GS and the "GS copy VS" while leaving one precious ES/VS fetch constant for indirect `GL_ARB_shader_draw_parameters` in the real VS)…

**Comment by Flakebi** [comment]
The removal of pre-GFX10 affects LLPC, as it is tightly coupled to PAL. It does **not** affect LLVM. LLVM keeps its existing support for radeonsi and others.
