### ISSUE TITLE
dEQP-VK.graphicsfuzz.discard-in-loop

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#331]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[discard-in-loop.zip](https://github.com/GPUOpen-Drivers/llpc/files/3833403/discard-in-loop.zip)

**Comment by paulthomson** [comment]
Closing as this apparently does not reproduce.

**Comment by kuhar** [comment]
Sidenote: this does not validate:
```
ERROR: Fails to validate SPIR-V: 
error: 59: block <ID> 37[%37] exits the selection headed by <ID> 11[%11], but not via a structured exit
  %37 = OpLabel
```
