### ISSUE TITLE
dEQP-VK.graphicsfuzz.two-nested-do-whiles

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#333]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[two-nested-do-whiles.zip](https://github.com/GPUOpen-Drivers/llpc/files/3833408/two-nested-do-whiles.zip)

**Comment by kuhar** [comment]
This works for me on on the dev branch with assertions enabled. @paulthomson

**Comment by kuhar** [comment]
All the new issues (#330-#334) compile fine for me. Not sure if the issues are still reproducible.

**Comment by paulthomson** [comment]
Ah apologies for the noise. The issues fail for me using the latest build of the dev branch of https://github.com/GPUOpen-Drivers/AMDVLK

However, that repo may not be pulling in the latest dev branch of this repo. The actual build comes from here (in case I am doing something wrong): https://github.com/google/gfbuild-llpc/releases/tag/github%2Fgoogle%2Fgfbuild-llpc%2F06e4d24336a16ed10d305931804d75a4104dce35

**Comment by paulthomson** [comment]
Closing as this apparently does not reproduce.

**Comment by kuhar** [comment]
Sidenote: this does not validate:
```
ERROR: Fails to validate SPIR-V: 
error: 110: block <ID> 72[%72] exits the selection headed by <ID> 57[%57], but not via a structured exit
  %72 = OpLabel
```
