### ISSUE TITLE
dEQP-VK.graphicsfuzz.unreachable-continue-statement

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#334]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[unreachable-continue-statement.zip](https://github.com/GPUOpen-Drivers/llpc/files/3833409/unreachable-continue-statement.zip)

**Comment by kuhar** [comment]
This works for me on the current dev branch with assertions enabled. @paulthomson

**Comment by paulthomson** [comment]
Closing as this apparently does not reproduce.

**Comment by kuhar** [comment]
Sidenote: this does not validate:
```
ERROR: Fails to validate SPIR-V: 
error: 73: block <ID> 45[%45] exits the selection headed by <ID> 22[%22], but not via a structured exit
  %45 = OpLabel
```
