### ISSUE TITLE
Cannot build against upstream LLVM

### ISSUE THREAD

**Issue by Zakhrov** [GPUOpen-Drivers/llpc#347]
I tried to build LLPC against upstream LLVM by pointing the XGL_LLVM_SRC_PATH to point to my System-installed LLVM. Howerver LLPC fails to build by saying ``` Intrinsic::amdgcn_waterfall_begin ```
is not a valid intrinsic. Is there any way to work around this?

**Comment by dstutt** [comment]
No, you need to use the LLVM fork here: https://github.com/GPUOpen-Drivers/llvm-project to be able to build LLPC. It contains a few extra intrinsics that support explicit waterfall loops required by LLPC.

https://github.com/GPUOpen-Drivers/AMDVLK has a top-level README.md that takes you through the steps for building LLPC.

**Comment by nhaehnle** [comment]
We should say that we generally strive to be able to build against upstream LLVM and to reduce any such deltas, but unfortunately there have been cases like this one where we couldn't avoid the problem. The LLVM branch that David pointed out is very close to upstream though.

**Comment by Zakhrov** [comment]
Ok thanks for letting me know.
Any idea when the waterfall intrinsics will be upstreamed? LLPC and XGL take a couple of hours to build on my Kabini APU laptop

**Comment by dstutt** [comment]
It's on my list of things to do - but I can't give you an estimate of when it'll happen at the moment. It won't be in the next couple of weeks.

**Comment by daviessm** [comment]
Hate to be that person but if it hasn't been upstreamed for llvm-10.0.0, is there any chance of it happening for 11.0.0?

**Comment by kuhar** [comment]
As a workaround for slow compile times, you can fetch the docker images the CI produces to get nightly precompiled llpc with all the dependencies for ubuntu:
```
docker pull gcr.io/stadia-open-source/amdvlk_dev_release:nightly
```
Note that there are no nightly debug images yet.
