### ISSUE TITLE
NGG GS culling framework

### ISSUE THREAD

**Issue by amdrexu** [GPUOpen-Drivers/llpc#506]
I’m going to add NGG GS culling. The algebraic algorithms are the same as non-GS (see the function `NggPrimShader::DoCulling`). No change for this. The particular part for GS (compared to non-GS) is how to run the culling algorithms for each output primitives (triangle strip). The steps are:

1.	Run GS and generate output primitives.
2.	Revisit those output primitives’ connectivity data, fetch position data (three vertices), and perform culling (within a loop for all output primitives).
3.	If the primitive survives, set a survive bit mask and update connectivity data (change vertex indices accordingly because vertex compaction). If the primitive is culled, change the primitive connectivity data to NULL primitive (`0x80000000`).
4.	After above steps, the outputs will be: a group of survive bits (in LDS, will be use when exporting vertex positions and parameters), final survive output vertex count (will update original output vertex count), and updated primitive connectivity data (vertex compacted).

I attach a simulation program to illustrate and verify the processing. Welcome any discussion on unclear points. The small simulation program will be the prototype of future IR implementation.

**Comment by amdrexu** [comment]
[gs.zip](https://github.com/GPUOpen-Drivers/llpc/files/4334413/gs.zip)

**Comment by nhaehnle** [comment]
>     2. Revisit those output primitives’ connectivity data, fetch position data (three vertices), and perform culling (within a loop for all output primitives).

We have enough shader waves to have one thread per output primitive. So the loop should not be necessary.


>     3. If the primitive survives, set a survive bit mask and update connectivity data (change vertex indices accordingly because vertex compaction). If the primitive is culled, change the primitive connectivity data to NULL primitive (`0x80000000`).

So I guess this can work like:
```
switch active threads to per-output primitive
do culling calculations
bitmask of surviving primitives is in an SGPR
every wave32 writes one dword of surviving primitive bitmasks to LDS
barrier
switch active threads to per-output vertex
each thread pulls the bits of the output primitives that it could be contained in from LDS
determine final output vertex survive status
use subgroup scans (DPP) to compute mapping from original output vertex to compacted output vertex
write mapping to LDS
barrier
switch active threads to per-output primitive
fetch vertex mapping from LDS and update prim dword
export prim
switch to per-output vertex
fetch vertex mapping from LDS and export positions and parameters
```

**Comment by amdrexu** [comment]
@nhaehnle I think your framework is very similar to what we have done for non-GS culling. And I also believe this framework is more efficient for NGG GS non-culling shader compared to our existing design. It could avoid loop iteration, especially for such extreme case: just one input GS thread, emitting 256 output vertices.

Besides, we currently do vertex compaction in the end of original GS execution (since each GS thread could emit different number of output vertices, less than max_vertices. e.g. GS thread0 emits 10 vertices and GS thread1 emits 100 vertices, max_vertices=100). The base is active threads of per-input primitive. It causes the design logic unclear by doing tricky patching. I think with your design, we just need additional 256 BYTEs LDS space to store the vertex mapping (similar to `LdsRegionCompactThreadIdInSubgroup` in existing codes). Original design is to save LDS space but in view of GFX10's 32K LDS space, I believe it is not a problem. We are conservative. 

I will make an architectural change for existing NGG GS non-culling shader. Then culling is nartually added above it.

**Comment by amdrexu** [comment]
The preparation work is submitted: https://github.com/GPUOpen-Drivers/llpc/pull/611

**Comment by amdrexu** [comment]
A real implementation is: https://github.com/GPUOpen-Drivers/llpc/pull/666
