### ISSUE TITLE
Pack shader input/output framework

### ISSUE THREAD

**Issue by xuechen417** [GPUOpen-Drivers/llpc#523]
The overview of shader input/output packing is described in DdnPackShaderInputOutput.md. There are three phases. 
- Phase 1 [Done] Support packing input/output on XX-FS. 
Commit Id [40b2a6b, 9b88f2e]: basic framework
Commit Id [f1cebc3]: extend to handle 16-bit variables
Commit Id [884d3b0]: turn on `pack-in-out` option by default

- Phase 2 [Done]: Support input/output packing on tessellation pipeline. It packs on VS-TCS and TES-FS. Commit Id [8cd0205]

- Phase 3 [Done]: Refactor PatchResourceCollect pass to prepare for supporting GS pipeline
Commit Id [966a827]: refactor `InOutLocationInfo`
Commit Id [796032b, 764ee20, 2a57f8b, 37ff8e4]: refactor `inputLocInfoMap/outputLocInfoMap`

- Phase 4 [Done]: Support partial packing with dynamic indexing. Commit Id [3562e51]
- Phase 5 [Done]: Support input/output packing on geometry pipeline. It packs on VS/TES-GS and GS-FS. Commit Id [b1bc7a3]

For VS-TCS and VS/TES-GS,  scalares are treated as 32-bit and packed together.

**Comment by nhaehnle** [comment]
Sounds good, looking forward to more details :)

**Comment by xuechen417** [comment]
The last part (packing on GS) of this issue is still working in progress. Reopen it for the track.
