### ISSUE TITLE
Use .spvasm instead of .spvas for SPIR-V assembly text files

### ISSUE THREAD

**Issue by dnovillo** [GPUOpen-Drivers/llpc#529]
The standard suffix for SPIR-V assembly files is `.spvasm`.  LLPC currently uses `.spvas` which causes some mild confusion.

I have a patch that moves LLPC to use `.spvasm`.  I've renamed all the files in `llpc/test/shaderdb` but I'm not sure if this will cause friction in other external tools.  Should LLPC support both?

**Comment by amdrexu** [comment]
I think you can change it to `.spvasm` and let LLPC just support this one. Initially, we did use `.spvasm` as the extension name of assembly text files. This happened 4 years ago. At that time, there was no official name. Later, we found this was somewhat verbose so we aligned the name "as" with `spirv-as` tool name.

One internal tool might be broken by this change. But it is easy to fix the problem.

**Comment by dnovillo** [comment]
@amdrexu thanks.  I'll post the patch shortly.
