### ISSUE TITLE
LGC shader compilation interface

### ISSUE THREAD

**Issue by trenouf** [GPUOpen-Drivers/llpc#545]
LGC: shader compilation interface
==================

Further to [#507 LGC: shader compilation proposal](https://github.com/GPUOpen-Drivers/llpc/issues/507), this proposal concerns the LGC interface for shader compilation and later linking.

Current interface for pipeline compilation
----------------------------

The front-end compiles a whole pipeline using LGC APIs like this:

* Create `Pipeline` object, populate it with tuning options and pipeline state.

* For each shader stage, build IR module for it using `Builder` methods. (This part does not use the pipeline state if in BuilderRecorder mode.)

* Call `Pipeline::link` to link the one or more IR modules for shader stages into a pipeline IR module.

* At this point, the pipeline IR module is serializable for testing purposes (if in BuilderRecorder mode).

* Call `Pipeline::run` to generate that pipeline module into a pipeline ELF.

Proposed interface for shader compilation
---------------------------------

The front-end would compile a vertex-processing half-pipeline, or a fragment shader, or a compute shader, like this:

* Create `Pipeline` object, populate it with tuning options, and optionally some other pipeline state if it is available. One tuning option is "assume triangles".

* If the other half-pipeline is already available as a compiled ELF, give it to the `Pipeline` as it may aid more optimal shader input/output passing.

* Call a new `Pipeline` function to get the hash of that part of the supplied state that will affect the half-pipeline to be compiled. (That includes linker metadata from the other half-pipeline compiled ELF if supplied.)

* Front-end can hash that in with the input shader(s) to check its cache and retrieve a cached ELF.

* On cache miss:
  - For each shader stage, build IR module for it using `Builder` methods. (This part does not use the pipeline state if in BuilderRecorder mode.)
  - Call `Pipeline::link` to link the one or more IR modules into a single half-pipeline IR module.
  - At this point, the half-pipeline IR module is serializable for testing purposes (if in BuilderRecorder mode).
  - Call `Pipeline::run` to generate a half-pipeline ELF. Where pipeline state is absent, some scheme is used for link-time resolution, as proposed in #507.
  - Front-end can cache it with the hash it calculated above.

Proposed interface to link ELFs into pipeline ELF
-------------------------------

* Create `Pipeline` object, and populate it with the complete pipeline state. (This can be the same `Pipeline` object as above, if that suits how the front-end is doing its compilation.)

* From `Pipeline`, create new `Linker` object, providing it with the unlinked ELF(s).

* Call `Linker` method to get a (possibly empty) list of hashes of required prologs/epilogs (fetch shader, VS epilog, FS epilog, CS prolog).

* For each prolog/epilog:
  - Check cache for existing ELF; if found, give it to `Linker` object.
  - Otherwise, call `Linker` object to create the prolog/epilog ELF, and store ELF in the cache.

* Call `Linker` function to do final ELF link, generating pipeline ELF.

**Comment by nhaehnle** [comment]
To clarify, whenever you write "frontend", you mean a part of code that lives in the LLPC, right? So the client interface remains unchanged by this?

> On cache miss:
>  *  For each shader stage, build IR module for it using Builder methods. (This part does not use the pipeline state if in BuilderRecorder mode.)

This sounds sub-optimal. From a high-level, the shader should already be available as IR, or as bitcode that can easily be deserialized into IR, from when CreateShaderModule was executed.

I know this is *currently* not always the case because SPIR-V can have specialization constants in type definitions, which throws a wrench into that plan. But surely, the goal ought to be to get to the point where we can already have pre-optimized IR for each shader instead of re-parsing the SPIR-V when the shader appears in a pipeline compile?
