### ISSUE TITLE
[CI] Disable the amdvlk cron action on private forks

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#546]
It seems like more people are suffering from annoying workflow failures on their private forks, e.g., https://github.com/dnovillo/llpc/runs/566051267. A temporary workaround is to disable 3rd party actions in github settings for the affected forks.

The amdvlk workflow should only run on this repo. I tried to fix it before, but couldn't figure out the proper syntax. I asked on the github community forums and got this helpful answer: https://github.community/t5/GitHub-Actions/Run-scheduled-workflows-only-from-the-main-repository/m-p/45855#M6361.

I'm opening an issue to not forget about this and not to lose the link.

**Comment by dnovillo** [comment]
Thanks @kuhar.  Disabling third-party actions seems to be working for me.
