### ISSUE TITLE
Invalid llvm-ir generated in the emulib.

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#57]
When  function is defined with a particular calling convention, all calls to that function must use the same calling convention.  Some of the code generated in the emulation library does not follow this convention.  One example is in `@_Z9normalizeDv3_f`.  Here is the generated code:

```
; Function Attrs: nounwind
define spir_func <3 x float> @_Z9normalizeDv3_f(<3 x float>) #0 {
  %2 = call float @_Z6lengthDv3_f(<3 x float> %0)
  %3 = fdiv float 1.000000e+00, %2
  %4 = extractelement <3 x float> %0, i32 0
  %5 = extractelement <3 x float> %0, i32 1
  %6 = extractelement <3 x float> %0, i32 2
  %7 = call float @llvm.amdgcn.fmul.legacy(float %4, float %3)
  %8 = call float @llvm.amdgcn.fmul.legacy(float %5, float %3)
  %9 = call float @llvm.amdgcn.fmul.legacy(float %6, float %3)
  %10 = insertelement <3 x float> undef, float %7, i32 0
  %11 = insertelement <3 x float> %10, float %8, i32 1
  %12 = insertelement <3 x float> %11, float %9, i32 2
  ret <3 x float> %12
}
```

Notice the call to `@_Z6lengthDv3_f` does not have a calling convention mentioned, which means it defaults to the C calling convention.  However, the definition of `@_Z6lengthDv3_f` is

```
; Function Attrs: nounwind
define spir_func float @_Z6lengthDv3_f(<3 x float>) #0 {
  %2 = extractelement <3 x float> %0, i32 0
  %3 = extractelement <3 x float> %0, i32 1
  %4 = extractelement <3 x float> %0, i32 2
  %5 = fmul float %2, %2
  %6 = fmul float %3, %3
  %7 = fadd float %5, %6
  %8 = fmul float %4, %4
  %9 = fadd float %7, %8
  %10 = call float @llvm.sqrt.f32(float %9)
  ret float %10
}
```

Notice the calling convention is `spir_func`.  This can cause problems.  It does not for now because these function calls are inlined, and inlining does not notice the mismatch.  However, if this code is run through instcombine before inlining, the function call will be replaced by a store to and undefined address.  This will in turn be turned into a trap.

**Comment by trenouf** [comment]
Thanks Steven. I spotted that one too. Definitely need to think about it if we move to not inlining everything.

**Comment by mcoffin** [comment]
There are many more issues to address if we ever remove inlining. There's a bunch of usage of intrinsics which require immediate-only operands which are not *necessarily* being used with an immediate until the function finally gets inlined at the end of the day. It's why GPUOpen-Drivers/llvm@0587d403b8a27a6ed67e8c349112d075f2ba4a71is still needed to compile the llpc emulation library with LLVM right now

**Comment by jayfoad** [comment]
Is this still a problem now that the emulib has been removed (f21077a9ba554bbf1bccd008e626ca6ec47ed332)?
