### ISSUE TITLE
Undefined behaviour by invalid enum values

### ISSUE THREAD

**Issue by Flakebi** [GPUOpen-Drivers/llpc#636]
The values defined here
https://github.com/GPUOpen-Drivers/llpc/blob/090f200949cd66d89eaaad78c430adcef1ea19d7/lgc/include/lgc/state/Defs.h#L37-L40
are not actually members of the `BuiltInKind` enum.
https://github.com/GPUOpen-Drivers/llpc/blob/090f200949cd66d89eaaad78c430adcef1ea19d7/lgc/interface/lgc/BuiltInDefs.h#L54

Ubsan rightfully notices this as undefined behavior, they should be added to the enum here:
https://github.com/GPUOpen-Drivers/llpc/blob/090f200949cd66d89eaaad78c430adcef1ea19d7/lgc/interface/lgc/BuiltIns.h#L37-L41

Tagging @trenouf because I think he introduce that code.

**Comment by trenouf** [comment]
They should not be defined in interface/lgc/BuiltIns.h, because they are not part of the interface, and we don't want front-end code to be able to see them.

Why is it undefined behavior? What is the recommended way of defining an enum in an interface then extending it internally?

**Comment by amdrexu** [comment]
Originally, those built-ins are to extend enumerants defined in standard spirv.hpp header. We want to use the enumeration type yet assign internal values to them without changing the standard header (we are disallowed to make any modification in the header). But now, LGC has its own definitions. If possible, they could be safely defined in enum type. If they are invisible to front-end, they could stay in the relevant classes as static const members.

**Comment by Flakebi** [comment]
Enums are only meant to have the variants with which they are defined, assigning another value to them leaves it [unspecified](https://stackoverflow.com/a/8801031), so the compiler is free to optimize out that assignment.

I guessed that something like this would be the problem. There seems to be a way to “derive” enums explained here, looks a bit crazy though: https://stackoverflow.com/a/644651
There does not seem to be a way to have private enum variants in C++ though.
Otherwise, functions that need it could just take an `unsigned` instead of a `BuiltInKind` and the private values can also be defined as `unsigned` to allow both, enum values and private ones.

**Comment by Flakebi** [comment]
Ok, I’m not sure anymore, the allowed range might be bigger than enum values, so `enum BuiltInKind : unsigned` might work.
