### ISSUE TITLE
shaderdb test don't run correctly

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#65]
When I follow the instructions to run the test, every test fails because it cannot find SPVGEN.  The output from one of the tests is given below.  SPVGEN has been build.  I can see it in the build directory, but it is not on the path that is being looked for.  If I add the path to LD_LIBRARY_PATH, the tests start to work.

This is bad because the tests may work or fail because it will pick up whichever spvgen.so happens to be in my LD_LIBRARY_PATH, and not the one being built.  It also adds an extra step.  Something should be done in the build to ensure that the spvgen.so that is in the build directory is the only one that can be used.

```
stevenperron@stevenperron0:builds/Release ‹dev*›$ llvm/bin/llvm-lit -v llpc/test/shaderdb/gfx9/ObjFloat16_TestTrinaryMinMaxFuncs_lit.frag
-- Testing: 1 tests, 1 threads --
FAIL: LLPC_SHADERTEST :: shaderdb/gfx9/ObjFloat16_TestTrinaryMinMaxFuncs_lit.frag (1 of 1)
******************** TEST 'LLPC_SHADERTEST :: shaderdb/gfx9/ObjFloat16_TestTrinaryMinMaxFuncs_lit.frag' FAILED ********************
Script:
--
: 'RUN: at line 27';   /usr/local/google/home/stevenperron/llpc/amdvlk/drivers/xgl/builds/Release/llpc/amdllpc -spvgen-dir= -v -gfxip=9 /usr/local/google/home/stevenperron/llpc/amdvlk/drivers/llpc/test/shaderdb/gfx9/ObjFloat16_TestTrinaryMinMaxFuncs_lit.frag | /usr/local/google/home/stevenperron/llpc/amdvlk/drivers/xgl/builds/Release/llvm/bin/FileCheck -check-prefix=SHADERTEST /usr/local/google/home/stevenperron/llpc/amdvlk/drivers/llpc/test/shaderdb/gfx9/ObjFloat16_TestTrinaryMinMaxFuncs_lit.frag
--
Exit Code: 1

Command Output (stderr):
--
/usr/local/google/home/stevenperron/llpc/amdvlk/drivers/llpc/test/shaderdb/gfx9/ObjFloat16_TestTrinaryMinMaxFuncs_lit.frag:28:21: error: SHADERTEST-LABEL: expected string not found in input
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
                    ^
<stdin>:1:1: note: scanning from here
ERROR: Failed to load SPVGEN -- cannot compile GLSL
^
<stdin>:1:13: note: possible intended match here
ERROR: Failed to load SPVGEN -- cannot compile GLSL
            ^

--

********************
Testing Time: 0.10s
********************
Failing Tests (1):
    LLPC_SHADERTEST :: shaderdb/gfx9/ObjFloat16_TestTrinaryMinMaxFuncs_lit.frag

  Unexpected Failures: 1
```

**Comment by trenouf** [comment]
The idea is that the "-spvgen-dir" option you see on the amdllpc line should have the directory where it put spvgen.so when it built it. But it is empty in your output.

Did you try "make check-amdllpc" first? That might be needed to ensure everything is set up before you try using a manual llvm-lit.

**Comment by s-perron** [comment]
Yes, I did try `make check-amdllpc` first.  That is where I first saw the errors.  However, I updated all of the repos, and recompiled.  It started to work fine after that.

**Comment by trenouf** [comment]
I guess that makes sense as I changed the lit test running fairly recently, maybe a couple of weeks ago. Glad it works for you now.
