### ISSUE TITLE
NGG non-GS rework

### ISSUE THREAD

**Issue by amdrexu** [GPUOpen-Drivers/llpc#668]
We are going to rework original NGG non-GS framework. Recent performance tuning suggests we'd better to have some architectural changes. This ticket is to list the ongoing sub-tasks.

1. Subgroup compaction (cull the whole subgroup or not) is proved to be less useful. Vertex compaction is more flexible. `NggCompactMode` will remove the item `NggCompactSubgroup` and replace it with a new one for future use `NggCompactNone`, which means no vertex compaction.

2. Initially, the deferring attribute shading was done for vertex parameter data. All vertex position data were fetched before culling. Rather, we only need pos0 data before culling (or need cull distance data if cull distance culling is enabled), other position data are still treated as deferred attributes and should be fetched after culling and vertex compaction. The granularity is not perfect. 

3. Some special cases disable culling. They are:
(1) Vertex number < 16.
(2) gl_Position is not used in shader or is constant.
(3) Memory/resource write operation is involved. You can not do culling and compaction.

4. The major change are: group vertex compacted data together and don't allocate LDS region for them based on max subgroup thread count. Instead, use a emulated ES-GS ring to dynamically address the info and allocate required size. The region is: `LdsRegionPosData, LdsRegionDrawFlag, LdsRegionCullDistance, LdsRegionVertThreadIdMap, LdsRegionCompactXXX`

5. A single-wave subgroup optimization is under experiment. All primitive and vertex threads stay in one wave. This could avoid LDS barrier and many multiple-wave calculation.

6. Like 3, in the future, more pipeline states will be passed to compiler via primitive shader const buffer, such as primitive topology. The culling will be decided at run-time. So shader will use a calculated `cullingMode` flag (a SGPR) to execute culling code path or not. This is not only from the separated shader link requirement but also from an extension requirement introducing the concept of dynamic state.

**Comment by nhaehnle** [comment]
Sounds good, some questions:

>  2. Primitive ID is not used in API VS. Originally, the primitive ID distribution algorithm uses the primitive ID provided by primitive threads and assigns it to all forming vertices to overcome a HW limitation for API-VS. The limitation is HW only provides primitive ID per-primitive-thread and API-VS is expected to run in per-vertex-thread. The algorithm causes code unclearness.

I'm not sure what you're saying here. You mean to skip the primitive ID distribution when it isn't used by the VS? That sounds good to me.

> Rather, we only need pos0 data before culling (or need cull distance data if cull distance culling is enabled),

Don't we also want clip distances? If a primitive can be culled based on the clip distance, then doing so is correct.

**Comment by amdrexu** [comment]
> I'm not sure what you're saying here. You mean to skip the primitive ID distribution when it isn't used by the VS? That sounds good to me.

In OpenGL/Vulkan, we don't have such semantics `in int gl_PrimitiveID`. Of course, our hardware provides its value, but API shader doesn't have a way accessing it, if I remember correctly. So what I mean is to completely remove the processing of primitive ID distribution. This processing was originally only valid for API-VS.

> Don't we also want clip distances? If a primitive can be culled based on the clip distance, then doing so is correct.

Correct, if cull distance culling is enabled, cull distance should be recorded like what we have done for position. The values will take part in later culling algorithm.

**Comment by nhaehnle** [comment]
> > I'm not sure what you're saying here. You mean to skip the primitive ID distribution when it isn't used by the VS? That sounds good to me.
> 
> In OpenGL/Vulkan, we don't have such semantics `in int gl_PrimitiveID` in API VS. Of course, our hardware provides its value, but API VS shader doesn't have a way accessing it, if I remember correctly. So what I mean is to completely remove the processing of primitive ID distribution. This processing was originally only valid for API VS.

I see what you mean. However, my understanding is that in a VS-PS pipeline, the fragment shader can use PrimitiveID. In this case, the VS has to export the PrimitiveID as a parameter, which means that in VS-as-NGG, we still need to distribute the PrimitiveID to the vertex threads in order to do this export.

**Comment by amdrexu** [comment]
> which means that in VS-as-NGG, we still need to distribute the PrimitiveID to the vertex threads in order to do this export.

Yes, this is a case I didn't realize :)

**Comment by amdrexu** [comment]
All work is done.
