### ISSUE TITLE
SpirvLowerGlobal shouldn't visit the whole module

### ISSUE THREAD

**Issue by jayfoad** [GPUOpen-Drivers/llpc#725]
The SpirvLowerGlobal pass visits the whole module to find loads and stores to global variables, and call and return instructions. I think it would be more efficient to find the load and store instructions by iterating over the users of the global variable (and recursively the users of any getelementptr instructions), and to find the call instructions by iterating over users of the callee, and to find the return instructions by looking at the terminator of each basic block. This should be faster when visiting very large functions with very few load/store/call/return instructions.

**Comment by amdrexu** [comment]
The original visitors were always based on module not function uses. At the beginning of LLPC, we don't have enough time to evaluate the performance. Feel free to make changes towards the right direction.

**Comment by bsaleil** [comment]
Fixed by https://github.com/GPUOpen-Drivers/llpc/pull/1537
