### ISSUE TITLE
Implement new control flow lowering based on reconverging CFG transform

### ISSUE THREAD

**Issue by nhaehnle** [GPUOpen-Drivers/llpc#758]
Tracking issue for the bulk of control flow lowering changes.

**Comment by kuhar** [comment]
Related LLVM RFC: [[llvm-dev] RFC: Introducing CfgTraits and type-erased CfgInterface / CfgBlockRef / CfgValueRef](https://groups.google.com/d/topic/llvm-dev/Vt4qsA3hkaw)

Revision stack:
1.  [D83094 Analysis: Add a GenericCycleInfo analysis](https://reviews.llvm.org/D83094)
1.  [D83093 DomTree: Define GraphTraits for GenericDomTreeBase ](https://reviews.llvm.org/D83093)
1.  [D83092 DomTree: Add findSiblingOfUncle helper ](https://reviews.llvm.org/D83092)
1.  [D83090 DomTree: Add TreeNode type alias ](https://reviews.llvm.org/D83090)
1.  [D83089 DomTree: Extract (mostly) read-only logic into type-erased base classes ](https://reviews.llvm.org/D83089)
1.  [D83088 Introduce CfgTraits abstraction ](https://reviews.llvm.org/D83088)
1.  [D83087 DomTree: remove explicit use of DomTreeNodeBase::iterator ](https://reviews.llvm.org/D83087)
1.  [D83086 DomTree: add private create{Child,Node} helpers ](https://reviews.llvm.org/D83086)
1.  [D83085 DomTree: Remove getRoots() accessor ](https://reviews.llvm.org/D83085)
1.  [D83084 DomTree: Remove the releaseMemory() method ](https://reviews.llvm.org/D83084)
1.  [D83083 DomTree: Remove getChildren() accessor ](https://reviews.llvm.org/D83083)
1.  [D83253 MachineBasicBlock: add printName method ](https://reviews.llvm.org/D83253)

**Comment by kuhar** [comment]
Related RFC: [[llvm-dev] [RFC] Introducing convergence control bundles and intrinsics](https://groups.google.com/g/llvm-dev/c/m3pnM3LU8tk/m/kUGZN10ABwAJ)
