### ISSUE TITLE
Fix cts tests of VK_KHR_buffer_device_address

### ISSUE THREAD

**Issue by xuechen417** [GPUOpen-Drivers/llpc#806]
dEQP-VK.memory_model.message_passing.ext.u32.\*physbuffer\* crash (.vert/.frag) or fail (.comp). It's a regression recently.
The following is a simplified vertex shader to describe the issue:
#version 450 core
#pragma use_vulkan_memory_model
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_shuffle : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_EXT_buffer_reference : enable
// DIM/NUM_WORKGROUP_EACH_DIM overriden by spec constants
layout(buffer_reference) buffer PayloadRef { uint x[]; };
layout (push_constant, std430) uniform PC {
   layout(offset = 0) PayloadRef payloadref;
};
void main()
{
   devicecoherent PayloadRef payload = payloadref;
   uint bufferCoord = 2;
   payload.x[bufferCoord] = bufferCoord;
}
// LLPC pipeline before-patching results
%0 = type <{ [4294967295 x i32] }>

; Function Attrs: nounwind
define spir_func void @lgc.shader.VS.main() local_unnamed_addr #0 !spirv.ExecutionModel !4 !lgc.shaderstage !4 {
.entry:
  %0 = call [8 x i8] addrspace(4)* @lgc.push.const.p4a8i8() #1
  %1 = bitcast [8 x i8] addrspace(4)* %0 to %0 addrspace(1)* addrspace(4)*
  %2 = load %0 addrspace(1)*, %0 addrspace(1)* addrspace(4)* %1, align 8
  %3 = getelementptr %0, %0 addrspace(1)* %2, i64 0, i32 0, i64 2
  store atomic i32 2, i32 addrspace(1)* %3 unordered, align 4
  ret void
}
For vertex shader or fragment shader tests, pushConstOffset.dwordSize gets 0 in gatherUserDataUsage(), which makes addUserDataArgs() crash.
For compute shader, the tests fails.
@trenouf Could you give some suggestions on the issue?

**Comment by nhaehnle** [comment]
Were you able to track down the change at fault of the crash using `git bisect`?

**Comment by xuechen417** [comment]
Thanks. The assertions help me find the break changes. I will try git bisect next time.

**Comment by amdrexu** [comment]
I think this is resolved.

**Comment by xuechen417** [comment]
> I think this is resolved.

Yes, it is resolved in 394d5539 ("Fix physical buffer pointer in push constants").
