### ISSUE TITLE
Implement YCbCr conversion for GFXIP=8

### ISSUE THREAD

**Issue by mwezdeck** [GPUOpen-Drivers/llpc#832]
YCbCr conversion is implemented only for GFX IP = 9,10. I would like to implement this feature for GFX IP=8.

**Comment by nhaehnle** [comment]
Yes, feel free to go ahead :+1:

**Comment by mwezdeck** [comment]
I'm trying to understand the code, however I don't understand one thing.

There is member field unsigned tileOptimal : 1 In SamplerYCbCrConversionMetaData in word1 structure. I don't see where it is initialized at all. However, in  YCbCrAddressHandler::genHeightAndPitch function there is decision made based on this bit.

Can somebody explain this to me?

**Comment by mwezdeck** [comment]
IS it safe to make decision based on compiler initialized variable?

**Comment by jiaxie-amd** [comment]
> I'm trying to understand the code, however I don't understand one thing.
> 
> There is member field unsigned tileOptimal : 1 In SamplerYCbCrConversionMetaData in word1 structure. I don't see where it is initialized at all. However, in YCbCrAddressHandler::genHeightAndPitch function there is decision made based on this bit.
> 
> Can somebody explain this to me?

When  #743  and a latter code clean up change is merged, the tileOptimal bit should no longer being used in compiler.

**Comment by amdrexu** [comment]
This task seems finished.
