### ISSUE TITLE
LLPC crashes on shader that tries to apply OpCopyObject to void

### ISSUE THREAD

**Issue by afd** [GPUOpen-Drivers/llpc#833]
LLPC errors with:

```
amdllpc: /home/runner/work/gfbuild-llpc/gfbuild-llpc/vulkandriver/drivers/llvm-project/llvm/lib/IR/DataLayout.cpp:708: llvm::Align llvm::DataLayout::getAlignment(llvm::Type*, bool) const: Assertion `Ty->isSized(
) && "Cannot getTypeInfo() on a type that is unsized!"' failed.
```

on the attached SPIR-V.

[tofile.zip](https://github.com/GPUOpen-Drivers/llpc/files/4931981/tofile.zip)

Command used:

```
amdllpc -val=false -gfxip=9.0.0 -verify-ir -auto-layout-desc shader.frag.spv -o shader.frag.spv.out
```

I opened a SPIR-V spec issue to see whether OpCopyObject should really be legal on something of type void - the spec currently says that it is.

**Comment by lifpan** [comment]
I think this is illegal. See SPIR-V SPEC section **2.2.1 Instructions**
> Object: An instantiation of a non-void type, either as the Result <id> of an operation, or created through OpVariable.

**Comment by LLJJDD** [comment]
This issue happens to be fixed by #894, which is originally intended to fix #834. Can be closed.

**Comment by afd** [comment]
Thanks.  @lifpan I will follow up with Khronos regarding getting the SPIR-V specification and validator improved if the working group agree with your analysis that this is invalid.

**Comment by afd** [comment]
@LLJJDD I don't know whether we care about this - because as @lifpan pointed out the spec should probably change to make it explicitly invalid to apply OpCopyObject to void, but the attached still crashes LLPC.

We have changes spirv-fuzz so that it shouldn't emit object copies of void in the future, but thought I'd attach this here (rather than opening a new issue) in case you want to make LLPC robust against this.

[tofile.zip](https://github.com/GPUOpen-Drivers/llpc/files/5141788/tofile.zip)

**Comment by afd** [comment]
You are right - sorry.  I had failed to realise that the latest LLPC that AMDVLK checks out did not include this fix.  Closing the issue.

**Comment by dnovillo** [comment]
@afd the test `llpc/test/shaderdb/fuzzer/GraphicsFuzz_TestOpCopyObjectOfVoidType.spvasm` is now failing because recent SPIRV-Tools are rejecting `OpUndef` for `%void` type.  I believe this test was guarding against an LLVM failure before.  Should we remove it or leave it with an expected error like:

```
ERROR: Fails to validate SPIR-V:
error: 8: Cannot create undefined values with void type
  %462 = OpUndef %void
```

Either is fine with me.  But the actual SPIR-V in this file is now invalid.

**Comment by afd** [comment]
Yes - the working group indeed decided to make this invalid and I implemented the validation - didn’t think about this test! I suggest removing it.

**Comment by dnovillo** [comment]
Thanks.  I've sent https://github.com/GPUOpen-Drivers/llpc/pull/1078 for review.
