### ISSUE TITLE
LLPC crashes on shader that uses bvec4

### ISSUE THREAD

**Issue by afd** [GPUOpen-Drivers/llpc#836]
LLPC errors with:

```
amdllpc: /home/runner/work/gfbuild-llpc/gfbuild-llpc/vulkandriver/drivers/llpc/llpc/translator/lib/SPIRV/SPIRVReader.cpp:3557: llvm::Constant* SPIRV::SPIRVToLLVM::transInitializer(SPIRV::SPIRVValue*, llvm::Type*): Assertion `initializer->getType()->isIntegerTy(1)' failed.
```

on the attached SPIR-V.  I'm attaching an Amber test that has three equivalent shaders - LLPC crashes on the version that declares a bvec4 variable initialized to (false, false, false, false).  Also in the archive is minimized SPIR-V that reproduces the issue.

[tofile.zip](https://github.com/GPUOpen-Drivers/llpc/files/4932668/tofile.zip)

Command used:

```
amdllpc -val=false -gfxip=9.0.0 -verify-ir -auto-layout-desc shader.frag.spv -o shader.frag.spv.out
```

Issue found using spirv-fuzz.

**Comment by trenouf** [comment]
What happens if you don't say "-val=false"?

**Comment by kuhar** [comment]
I field pull request with the test from this and the other issues.
This particular one seems to only require assertions to fail.

**Comment by amdrexu** [comment]
Fixed.
