### ISSUE TITLE
Generating readfirstlane efficiently when values are used as operands that must be uniform

### ISSUE THREAD

**Issue by nhaehnle** [GPUOpen-Drivers/llpc#840]
This issue is prompted by #811, which contains a partial and unfortunately partially incorrect or at least fragile attempt to fix the underlying problem, which occurs in IR such as:
```llvm
  %idx = add i32 %a, %b
  %desc.ptr = getelementptr <8 x i32>, ... %desc.base, i32 %idx
  %descriptor = load <8 x i32>, ... %desc.ptr
  call void @image_intrinsic(..., <8 x i32> %descriptor, ...)
```
According to the SPIR-V spec, we know that `%descriptor` must be uniform (assuming no NonUniform decoration). This information should be propagated to `%idx` so that we only need a single 32-bit readfirstlane, and the descriptor load can use a scalar load.

Furthermore, if %a can be proven to be uniform in some other way, then in fact we should put the readfirstlane on %b, so that the add can already be lowered as `s_add_u32`.

However, there are also limitations. Consider (pseudo-LLVM):
```llvm
  %idx = add i32 %a, %b
  if (condition) {
    %desc.ptr = getelementptr <8 x i32>, ... %desc.base, i32 %idx
    %descriptor = load <8 x i32>, ... %desc.ptr
    call void @image_intrinsic(..., <8 x i32> %descriptor, ...)
  }
```
If `condition` is itself divergent, then it could be the case that `%idx` is in general non-uniform, but it is uniform for all lanes which enter the if-block. In this case, the readfirstlane should be inserted on the `%idx`, so that the load can still be a scalar load, but the readfirstlane **must** be inside the if-block, otherwise it may incorrectly pick up the index from another lane that doesn't enter the if-block.

So to summarize, while #811 makes a useful effort to improve readfirstlane for a narrow case, this is really a more general problem:

1. We can sometimes push the readfirstlane even further than is attempted by #811.
2. Sometimes, we can actually only push it less far.
3. The same logic applies to other occurrences of readfirstlane as well.

Ideally, we would solve this problem as follows:

1. Early in the compiler pipeline (e.g. SPIRVReader), insert a readfirstlane directly on the descriptor.
2. As part of the middle-end optimization pipeline, run a pass which optimizes readfirstlane using the considerations mentioned above. The `DivergenceAnalysis` can be used to find cases such as the `add` where one operand is already known to be uniform.

@xuechen417 Is addressing this properly something that you could take on, considering you're working in the area? It is a larger project though, but it is a useful optimization.

Cc @amdrexu @jinjianrong

**Comment by xuechen417** [comment]
I would like to take on it. I am trying to digest your general solution.

**Comment by trenouf** [comment]
Sounds like a good plan to me.

**Comment by xuechen417** [comment]
@nhaehnle I'm not sure whether my understanding of the solution in #840 is correct. 

_1.  Early in the compiler pipeline (e.g. SPIRVReader), insert a readfirstlane directly on the descriptor._
- What's the reason for it? 
- Does that mean we don't need enforceUniformIndex for various methods in ImageBuilder class and put enforceUniformIndex in the new pass?
- I try to insert a readfirstlane on the descriptor in getImageDesc by checking ImageFlagNonUniformImage and ImageFlagNonUniformSampler, is it right?

_2. As part of the middle-end optimization pipeline, run a pass which optimizes readfirstlane using the considerations mentioned above. The DivergenceAnalysis can be used to find cases such as the add where one operand is already known to be uniform._
- Why put the readfirstlane pass in the middle-end optimization?
- In the new pass for readfirstlane optimization, 
  -use enforceUniformIndex change to insert a readfirstlane on %idx
  -use DivergenceAnalysis to determine whether need to push the readfirstlane on %b (push further) or put the readfirstlane inside if-block (push less far).
  -`%idx=add %a, %b` should be `%idx=mul %a, %b`, right?

_3. The same logic applies to other occurrences of readfirstlane as well_
- Could you show me an example for the occurrence of readfirstlane?

**Comment by xuechen417** [comment]
@nhaehnle In indexDescPtr, the following instructions sequences are generated
```
  Value *ptr = getBuilder()->CreateExtractValue(base, 0);
  Value *stride = getBuilder()->CreateExtractValue(base, 1);
  index = getBuilder()->CreateMul(index, stride);
  if (!isNonUniform && !isa<Constant>(index)) {
    // For a non-constant but uniform index, mark it uniform.
    index = getBuilder()->CreateIntrinsic(Intrinsic::amdgcn_readfirstlane, {}, index);
  }

  // Do the indexing operation by GEPping as a byte pointer.
  Type *ptrTy = ptr->getType();
  ptr = getBuilder()->CreateBitCast(ptr,
                                    getBuilder()->getInt8Ty()->getPointerTo(ptr->getType()->getPointerAddressSpace()));
  ptr = getBuilder()->CreateGEP(getBuilder()->getInt8Ty(), ptr, index);
```
I have no idea of what kind of case that has a if-block between Mul and GEP. Could you please give some hint about the glsl source or spv text looks like to generate the if-block pseudo-llvm?

**Comment by nhaehnle** [comment]
> _1. Early in the compiler pipeline (e.g. SPIRVReader), insert a readfirstlane directly on the descriptor._
> 
>     * What's the reason for it?

It models the behavior of the conceptual image instruction: the image instruction will always execute with a uniform descriptor (enforced by the readfirstlane). If the incoming descriptor is non-uniform, the behavior is undefined (it just takes the descriptor from one lane).

>     * Does that mean we don't need enforceUniformIndex for various methods in ImageBuilder class and put enforceUniformIndex in the new pass?

Some version of enforceUniformIndex, yes.

>     * I try to insert a readfirstlane on the descriptor in getImageDesc by checking ImageFlagNonUniformImage and ImageFlagNonUniformSampler, is it right?

It is best to insert the readfirstlane in the same place where the waterfall logic is inserted when the NonUniform decoration is present. This would mean the ImageBuilder, i.e. where enforceUniformIndex is called today.


> _2. As part of the middle-end optimization pipeline, run a pass which optimizes readfirstlane using the considerations mentioned above. The DivergenceAnalysis can be used to find cases such as the add where one operand is already known to be uniform._
> 
>     * Why put the readfirstlane pass in the middle-end optimization?

That is the most natural place for it: it is an optimization.


>     * In the new pass for readfirstlane optimization,
>       -use enforceUniformIndex change to insert a readfirstlane on %idx
>       -use DivergenceAnalysis to determine whether need to push the readfirstlane on %b (push further) or put the readfirstlane inside if-block (push less far).
>       -`%idx=add %a, %b` should be `%idx=mul %a, %b`, right?

What I am talking about is more general. Consider a shader that does some calculations for indexing:
```
  uint materialIdx = ...;
  uint idx = 10 + 3 * materialIdx;
  x = texture(textureArray[idx], ...);
```
Currently, we generate code like (pseudo-code):
```
  uint materialIdx = ...; // VGPR
  uint idx = 10 + 3 * materialIdx; // VGPR
  uint sgprIdx = readfirstlane(idx); // SGPR
  T descriptor = textureArray[sgprIdx];
  x = texture(descriptor, ...);
```
But really we can "push" the readfirstlane further:
```
  uint materialIdx = readfirstlane(...); // SGPR
  uint idx = 10 + 3 * materialIdx; // SGPR
  T descriptor = textureArray[idx];
  x = texture(descriptor, ...);
```
So the idea of the issue is that we initially start with the readfirstlane close to the `texture` builtin from the SPIRVReader:
```
  uint materialIdx = ...; // VGPR
  uint idx = 10 + 3 * materialIdx; // VGPR
  T descriptor = textureArray[idx]; // VGPR
  T sgprDescriptor = readfirstlane(descriptor);
  x = texture(descriptor, ...);
```
And then a separate transform pushes the readfirstlane as high as it can.

**Comment by xuechen417** [comment]
> > * I try to insert a readfirstlane on the descriptor in getImageDesc by checking ImageFlagNonUniformImage and ImageFlagNonUniformSampler, is it right?
 > > ```
> 
> It is best to insert the readfirstlane in the same place where the waterfall logic is inserted when the NonUniform decoration is present. This would mean the ImageBuilder, i.e. where enforceUniformIndex is called today.
>
You said "start with the readfirstlane close to the texture builtin from the SPIRVReader". Do you actually mean ImageBuilder? NonUniform decoration is first present in SPIRVToLLVM::getImageDesc. I think inserting a readfirstlane on the descriptor here needs change one place, but the waterfall logic scatters in many methods in ImageBuilders. 

> *That is the most natural place for it: it is an optimization.
I have a question. We use track back through to find the descriptor index until meeting call i8 addrspace(4)* @lgc.descriptor.set. If the new pass is put in Patch::addOptimizationPasses,  the stopper call has dispeared.
