### ISSUE TITLE
Move known-uniform values from VGPRs back to SGPRs where possible and beneficial

### ISSUE THREAD

**Issue by nhaehnle** [GPUOpen-Drivers/llpc#844]
There are situations where values that are known to be uniform nevertheless end up in VGPRs because they are results of operations that are only supported as vector instructions. Some examples:

* Floating point operations.
* Loads from a uniform address that must nevertheless go through V$, e.g. to ensure coherence / memory model properties.
* image_get_resinfo and other image-related operations (see #843).

In these cases, it can be beneficial to explicitly move the values into SGPRs using readfirstlane. The readfirstlane incurs a pipeline switching cost, but this cost may be worth it if:

* Moving the value to an SGPR allows many subsequent instructions to be executed as SALU instead of VALU.
* The value has a long live range, and moving it to an SGPR helps reduce register pressure.

The cost-benefit trade-off can only be judged accurately late during compilation, so this should be done in the backend (LLVM). Ideally, we'd do it as part of GlobalISel register bank selection (let's not implement this redundantly for both GlobalISel and SelectionDAG).

When embarking on this issue, we should spend some time to discuss the algorithmic design for how best to do this. Consider for example in some cases, the benefit of moving instructions from SALU to VALU can only be achieved when readfirstlane is applied to multiple values simultaneously.

See also the related issue #840.

@jinjianrong @amdrexu @dstutt

**Comment by yjaelex** [comment]
What is pipeline switching cost of readfirstlane? Is it some kind of wait or bubble in the shader engine pipeline?

Alex

**Comment by dstutt** [comment]
I'm not sure what you mean by the last paragraph. Did you mean SALU to VALU (or the other way around)?

Also, if you meant VALU to SALU - presumably you are saying that the optimisation may only be worth it when we can pay the pipeline switching cost fewer times by grouping the readfirstlanes?

**Comment by nhaehnle** [comment]
> What is pipeline switching cost of readfirstlane? Is it some kind of wait or bubble in the shader engine pipeline?

Yeah, the result of the v_readfirstlane isn't immediately available for scalar instructions, so if the only benefit of the v_readfirstlane would be to turn 2 or 3 VALU instructions into SALU ones, it's probably not worth it in most cases.

**Comment by tjb9821** [comment]
i want to know, Which openGl API can be compiled into the image_get_resinfo directive

**Comment by amdrexu** [comment]
> image_get_resinfo

We don't use image_get_resinfo now. Instead, we extract the info from resource descriptor with ALU operations. Initially, textureSize()/imageSize() in GLSL was mapped to image_get_resinfo hardware instruction.
