### ISSUE TITLE
Open-coded implementation of image_get_resinfo

### ISSUE THREAD

**Issue by nhaehnle** [GPUOpen-Drivers/llpc#845]
`image_get_resinfo` does not actually access memory, so invoking an image instruction for its purpose is quite expensive.

Instead, we can implement its functionality using bit manipulation. For example, querying the size can be achieved by bit extraction to get the base level size plus some arithmetic, so a small number of typically scalar instructions. This avoids the round-trip through the texture unit and the s_waitcnt, and helps keep values in SGPRs.

When addressing this issue, keep in mind the changes to the resource descriptor format between gfx10 and older hardware, as well as the occasionally slightly different interpretations of fields based on the image dimensionality.

This issue was triggered by #843, but in the past I have seen shaders whose performance could be improved by this change.

**Comment by nhaehnle** [comment]
@Kai-AMD Is this something you could look into, given your work on #843? Also Cc @amdrexu

**Comment by Kai-AMD** [comment]
> @Kai-AMD Is this something you could look into, given your work on #843? Also Cc @amdrexu
@nhaehnle, Alex,Yan will go on implementing #845.
