### ISSUE TITLE
cached pass manager reuses previous metadata

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#882]
When generating glue shaders, we try to reuse the same pass manager.  The p[rinter pass in the pass manager owns](https://github.com/GPUOpen-Drivers/llvm-project/blob/amd-gfx-gpuopen-dev/llvm/lib/CodeGen/LLVMTargetMachine.cpp#L177) an `AMDGPUTargetStreamer` object which contains the [state of the Palmetadata](https://github.com/GPUOpen-Drivers/llvm-project/blob/amd-gfx-gpuopen-dev/llvm/lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h#L32).  This does not get reset between runs, and I do not see how to reset it.  So if multiple pipelines are compiled the metadata for glue shaders that were previously compile will contaminate the metadata for later glue shaders.

I think the only reasonable solution is to not cache the pass manager.

**Comment by nhaehnle** [comment]
The MCTargetStreamer has a `finish` method. We're overriding this to emit the PAL metadata in the various streamers (ELF and Asm) -- perhaps the metadata could just be reset there?

**Comment by s-perron** [comment]
That seems like a good solution.  I've opened a differential in phabricator: https://reviews.llvm.org/D85667.
