### ISSUE TITLE
LLPC fails with "Stored value type does not match pointer operand type!"

### ISSUE THREAD

**Issue by afd** [GPUOpen-Drivers/llpc#926]
Found using LLPC c9c9a410565ece5c5a8735ddef7c8b24a8446db6.

[Files needed to reproduce the bug](https://github.com/GPUOpen-Drivers/llpc/files/5146493/tofile.zip)

Command to reproduce the bug:

```
amdllpc -gfxip=9.0.0 -verify-ir -auto-layout-desc tofile/shader.frag.spv -o temp.out
```

I see this output:

```
Stored value type does not match pointer operand type!
  store float addrspace(5)* %2, float addrspace(64)* addrspace(5)* %1, align 8
 float addrspace(64)*in function main
ERROR: LLVM FATAL ERROR: Broken function found, compilation aborted!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /data/binaries/built_in/gfbuild-llpc-c9c9a410565ece5c5a8735ddef7c8b24a8446db6-Linux_x64_Debug/llpc/bin/amdllpc -gfxip=9.0.0 -verify-ir -auto-layout-desc tofile/shader.frag.spv -o temp.out 
1.	Running pass 'Function Pass Manager' on module 'llpcfragment5'.
2.	Running pass 'Module Verifier' on function '@main'
```

Found using spirv-fuzz.

**Comment by ruiling** [comment]
@afd could you double check the llpc version? I could not reproduce the issue using latest llpc dev branch.

**Comment by afd** [comment]
@ruiling sorry - the commit hash refers to:

https://github.com/GPUOpen-Drivers/AMDVLK/commit/c9c9a410565ece5c5a8735ddef7c8b24a8446db6

This indeed doesn't use the latest llpc dev commit.  Later on I'll check whether the original unreduced shader fails with the latest dev commit.  If not then I guess this issue has been independently fixed.

**Comment by afd** [comment]
I tried this with 6adfe96fc4f0a0e7680e827eed48eed8d28cb4dc and it indeed does not reproduce, so must have been independently fixed.

I know for future that the latest commit used by GPUOpen-Drivers/AMDVLK doesn't use the latest dev commit of llpc.
