### ISSUE TITLE
LLPC fails after a long time with "LLVM FATAL ERROR: branch size exceeds simm16"

### ISSUE THREAD

**Issue by afd** [GPUOpen-Drivers/llpc#934]
Found using LLPC 6adfe96fc4f0a0e7680e827eed48eed8d28cb4dc.

This issue might be regarded as low priority since it requires a shader with a large number of function calls to trigger.  Nevertheless, it could be important if there is a need for LLPC to perform well on very large shaders such as ubershaders.

Files needed to reproduce the issue attached in comment below.

This contains two different shaders (with associated .asm files):

- bad_temp_2163.spv
- inlined.spv - obtained from bad_temp_2163.spv by running spirv-top with --merge-return --inline-entry-poins-exhaustive

I find that running LLPC on bad_temp_2163.spv leads to an LLVM fatal error after 1 minute:

```
amdllpc -gfxip=9.0.0 -verify-ir -auto-layout-desc tofile/bad_temp_2163.spv -o temp.out
```

I see this output:

```
ERROR: LLVM FATAL ERROR: branch size exceeds simm16
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /data/llpc/drivers/xgl/builds/Release64/compiler/llpc/amdllpc -gfxip=9.0.0 -verify-ir -auto-layout-desc bad_temp_2163.spv 
1.	Running pass 'CallGraph Pass Manager' on module 'lgcPipeline'.

```

Looking at the shader, it has a lot of function calls that would lead to a very large module if they were fully inlined.

I used spirv-opt to perform full inlining, which is where inlined.spv comes from.  LLPC does *not* crash on inlined.spv, but takes 1m9s to process it.

Issue found using spirv-fuzz.

**Comment by afd** [comment]
Here are the files needed to reproduce the issue:

[tofile.zip](https://github.com/GPUOpen-Drivers/llpc/files/5155033/tofile.zip)

**Comment by kuhar** [comment]
This reproduces on builds with and without assertions. I added the spirv to our test suite.

**Comment by kuhar** [comment]
This test sometimes explodes in out presubmit tests: https://github.com/GPUOpen-Drivers/llpc/pull/952/checks?check_run_id=1070354992.

IMO we should prioritize fixing this.

**Comment by ruiling** [comment]
I tried newer llvm version, the spv can compile successfully, so I guess somebody else fix the issue.
commit 240f3dd769edd6615fa478ecb9f7a761922ac026 (origin/amd-gfx-gpuopen-dev, origin/HEAD, amd-gfx-gpuopen-dev)
Merge: c72fe645f96 4ef4636769e
Author: Tim Renouf <tim.renouf@amd.com>
Date:   Thu Sep 10 19:52:42 2020 +0100

    Overwritten with: 4ef4636769e7 [AMDGPU] Set DS alignment requirements to be more strict.
    
    Based on upstream llvm : be35264ab5a3 Wordsmith RegionBranchOpInterface verification errors

**Comment by ruiling** [comment]
since the test is removed by #955, I think we need to close the issue? @kuhar @afd

**Comment by afd** [comment]
Yes, makes sense.
