### ISSUE TITLE
Use NewGVN and remove special-cases for phi nodes in PatchPeepholeOpt

### ISSUE THREAD

**Issue by nhaehnle** [GPUOpen-Drivers/llpc#957]
Shader code sometimes ends up containing non-trivial equivalent phi nodes in loops. See below for an example.

PatchPeepholeOpt has some very hard-coded logic in `visitPhiNode` that ought to be able to detect and simplify the example below (`%y1` and `%y2` playing the role of `phiNode` and `otherPhiNode`, respectively). However, that logic is very specific to a single special case. We ought to be able to handle this more generally.

`-newgvn` already does this: it successfully simplifies the phi nodes in the example below. We should investigate using NewGVN in our pass pipeline and removing the hard-coded logic in PatchPeepholeOpt. At the same time, we should consider removing the code that tries to optimize phi nodes with identical incoming values. SimplifyCFG should already be doing this.

Here's the example:
```
define i32 @main() {
entry:
  br label %A

A:
  %x1 = phi i32 [ 0, %entry ], [ %y2, %C ]
  %x2 = phi i32 [ 0, %entry ], [ %y1, %C ]
  %a = call i1 @foo()
  br i1 %a, label %Ap, label %B1

Ap:
  %b = call i1 @bar()
  br i1 %b, label %B2, label %B3

B1:
  %add = add i32 %x1, 1
  br label %C

B2:
  %b2 = call i1 @bar()
  br label %C

B3:
  %b3 = call i1 @baz()
  br label %C

C:
  %y1 = phi i32 [ %add, %B1 ], [ %x1, %B2 ], [ %x1, %B3 ]
  %y2 = phi i32 [ %add, %B1 ], [ %x2, %B2 ], [ %x2, %B3 ]
  %c = call i1 @baz()
  br i1 %c, label %A, label %out

out:
  %r = add i32 %y1, %y2
  ret i32 %r
}

declare i1 @foo()
declare i1 @bar()
declare i1 @baz()
```

cc @amdrexu @LLJJDD @dstutt

**Comment by ruiling** [comment]
I have asked @LLJJDD to re-investigate the problem this optimization tries to fix, if GVN solve such problem well, I think the optimization can be entirely removed. If not, I think we can temporarily refactor the code and fix the issues in the code and see whether we can upstream into LLVM later.

**Comment by nhaehnle** [comment]
One thing to keep in mind is that only NewGVN seems to optimize those phi nodes, old GVN doesn't. We already have old GVN in our pass pipeline, maybe we can just switch that over to NewGVN.

**Comment by dstutt** [comment]
Just tried replacing GVN with NewGVN locally, and it at least passes testing.
