### ISSUE TITLE
SGPR spill to VGPR causes invalid load

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#981]
LLPC is generating code that will generate an address in VGPRs and move it to SGPRs for a load.  However, the code can potentially be run when `exec` is 0, which means the address is not generated, and the load happends from a random address.

I believe the fix should be to generate a branch to skip the code if `exec` becomes 0.

Compile [ps.spvasm.txt](https://github.com/GPUOpen-Drivers/llpc/files/5299365/ps.spvasm.txt) as an unlinked shader as follows:

```
spirv-as ps.spvasm.txt -o ps.spv --target-env spv1.3 && 
amdllpc -gfxip=9 ps.spv -o t.elf -amdgpu-conditional-discard-transformations -amdgpu-transform-discard-to-demote
```

When you disassemble ([t.s.txt](https://github.com/GPUOpen-Drivers/llpc/files/5299406/t.s.txt)) the spir-v there are three interesting observations that work together to cause the code to crash when run:

1. The update of `exec` that corresponds to the OpKill does not branch to the end if `exec` becomes 0.
1. The code related to selecting the address for the load of the descriptor is done in VGPRs and then moved to SGPR
1. The code related to the group operation is not removed even if it is unused.

When this code is run and every thread is killed, it will keep running the code to perform the group operation.  The code the select the value for the address will not be execute by any thread because `exec` is 0 and they are vector instructions.  However, the `v_readfirstlane_b32 s0, v0` will store what is essentially a random value into `s0`, which is used as the address for the load.  These instructions will be executed because they are scalar instruction.

If the group operation is replaced with a store to an output, then code to branch if all threads are killed is added.

**Comment by s-perron** [comment]
sorry this is the correct spir-v: 
[ps.spvasm.txt](https://github.com/GPUOpen-Drivers/llpc/files/5299618/ps.spvasm.txt)

**Comment by trenouf** [comment]
Should the code in lib/Target/AMDGPU/SIRemoveShortExecBranches.cpp consider a readfirstlane to be "has unwanted effects when exec empty"? Is it the code in there that is removing the branch? Or @perlfu is this more a special case to do with kill?

**Comment by nhaehnle** [comment]
> Should the code in lib/Target/AMDGPU/SIRemoveShortExecBranches.cpp consider a readfirstlane to be "has unwanted effects when exec empty"?

https://github.com/llvm/llvm-project/blob/51323fe2b89e976dc53356299d5cc3daeaaee5a7/llvm/lib/Target/AMDGPU/SIInstrInfo.cpp#L3142

So this is really specific to OpKill. Recall that we try to early-exit the wave when kill turns EXEC=0, but we can't do that in nested control flow. This is one more argument in favor of doing the exo-skeleton thing that I presented internally a while ago, but that only works in the new control flow framework.

For correctness, we can probably undo the optimization which converts OpKill into conditional kill -- which is a shame, but also an incentive to finally solve it right :)

**Comment by s-perron** [comment]
@nhaehnle @trenouf Remember this uses the discard-to-demote transformation.  It seem to do the right thing if that transformation is turned off.  It may not be related to OpKill, but to OpDemoteToHelper.

**Comment by s-perron** [comment]
I have looked into this further.  

When the option `-amdgpu-transform-discard-to-demote` is used, kills are turned into "demote" instructions.  This means that the threads that are killed are still suppose to run normally if something in their quad has not been killed, but they are not to export any values.  The code that does the demotion happens [here](https://github.com/GPUOpen-Drivers/llvm-project/blob/amd-gfx-gpuopen-dev/llvm/lib/Target/AMDGPU/AMDGPUConditionalDiscard.cpp#L169).  Note that it folds the branch that led to the kill the demote is replacing, causing causing the rest of the code to be executed even if every thread has been demoted.  This is how the code ends up executing even if exec is 0.

So now we ask, why do we fold the branch?  This is related to the way in which the code whole quad mode (WQM) code is generated.  I have modified `AMDGPUConditionalDiscard` to generate the same branches it would when it is not replacing kills with demote, but to still replace the kills with demote.  The problem with this is demonstrated in this [test](https://github.com/GPUOpen-Drivers/llvm-project/blob/amd-gfx-gpuopen-dev/llvm/test/CodeGen/AMDGPU/discard-optimization.ll#L142).

If the branch is not folded the final code is:

```
wqm_kill_to_demote1:                    ; @wqm_kill_to_demote1
; %bb.0:                                ; %.entry
        s_mov_b64 s[12:13], exec
        s_wqm_b64 exec, exec
        v_cmp_gt_f32_e32 vcc, 0, v1
        s_and_b64 s[12:13], s[12:13], vcc             **<-- compare to determine which branches are demoted**
        s_wqm_b64 s[14:15], s[12:13]                  **<-- Enable any thread with a live thread in its quad**
        s_and_b64 exec, exec, s[14:15]                **<-- Update exec to reflect this**
        s_cbranch_execz BB5_4
; %bb.1:                                ; %.entry
                                        ; implicit-def: $vgpr1_vgpr2_vgpr3_vgpr4
        s_and_saveexec_b64 s[14:15], vcc           **<-- Now execute the branch that was not folded breaking WQM**
        s_cbranch_execz BB5_3
; %bb.2:                                ; %.continue
        image_sample v0, v0, s[0:7], s[8:11] dmask:0x1
        s_waitcnt vmcnt(0)
        v_add_f32_e32 v0, v0, v0
        image_sample v[1:4], v0, s[0:7], s[8:11] dmask:0xf
BB5_3:                                  ; %.export
        s_and_b64 exec, exec, s[12:13]
        s_or_b64 exec, exec, s[14:15]
        s_waitcnt vmcnt(0)
        v_mov_b32_e32 v0, v1
        v_mov_b32_e32 v1, v2
        v_mov_b32_e32 v2, v3
        v_mov_b32_e32 v3, v4
        s_branch BB5_5
BB5_4:  
        exp null off, off, off, off done vm
        s_endpgm
BB5_5:
```

I'll need to look into this more to see if I can find the right solution.

**Comment by s-perron** [comment]
The proper solution for this will be larger than I can get done any time soon.

From what I can tell, the llvm-ir separates the demote and kill instructions from the branch.  For example, after `AMDGPUConditionalDiscard` a kill will get turned into something like:

```
  %21 = fcmp olt float %20, 0.000000e+00
  %22 = xor i1 %21, true
  call void @llvm.amdgcn.kill(i1 %22)
  br i1 %21, label %39, label %23
```

The kill is used to update the exec.  The the branch is treated like a normal branch.  It will update the exec, which is redundant because the kill already did it, then it will restore the exec at the merge point, which is also redundant.  This design does not work with demote, because the `SI whole quad mode` pass will enter WQM at the demote, and then be broken by the branch.

To generate correct and efficient code, we would need the branch to be implicit in the kill/demote instructions.  I believe @nhaehnle has been working on something that may be related.  We should discuss the proper solution for this at some point.

**Comment by s-perron** [comment]
Looks like this has been fixed.  Thanks.
